package net.minecraft.server;

import java.util.function.Consumer;

public class DebugReportAdvancementNether implements Consumer<Consumer<Advancement>> {

    public DebugReportAdvancementNether() {}

    public void accept(Consumer<Advancement> consumer) {
        Advancement advancement = Advancement.SerializedAdvancement.a().a(Blocks.RED_NETHER_BRICKS, new ChatMessage("advancements.nether.root.title", new Object[0]), new ChatMessage("advancements.nether.root.description", new Object[0]), new MinecraftKey("minecraft:textures/gui/advancements/backgrounds/nether.png"), AdvancementFrameType.TASK, false, false, false).a("entered_nether", (CriterionInstance) CriterionTriggerChangedDimension.b.a(DimensionManager.NETHER)).a(consumer, "nether/root");
        Advancement advancement1 = Advancement.SerializedAdvancement.a().a(advancement).a(Items.FIRE_CHARGE, new ChatMessage("advancements.nether.return_to_sender.title", new Object[0]), new ChatMessage("advancements.nether.return_to_sender.description", new Object[0]), (MinecraftKey) null, AdvancementFrameType.CHALLENGE, true, true, false).a(AdvancementRewards.a.a(50)).a("killed_ghast", (CriterionInstance) CriterionTriggerKilled.b.a(CriterionConditionEntity.a.a().a(EntityTypes.GHAST), CriterionConditionDamageSource.a.a().a(true).a(CriterionConditionEntity.a.a().a(EntityTypes.FIREBALL)))).a(consumer, "nether/return_to_sender");
        Advancement advancement2 = Advancement.SerializedAdvancement.a().a(advancement).a(Blocks.NETHER_BRICKS, new ChatMessage("advancements.nether.find_fortress.title", new Object[0]), new ChatMessage("advancements.nether.find_fortress.description", new Object[0]), (MinecraftKey) null, AdvancementFrameType.TASK, true, true, false).a("fortress", (CriterionInstance) CriterionTriggerLocation.b.a(CriterionConditionLocation.a("Fortress"))).a(consumer, "nether/find_fortress");
        Advancement advancement3 = Advancement.SerializedAdvancement.a().a(advancement).a(Items.MAP, new ChatMessage("advancements.nether.fast_travel.title", new Object[0]), new ChatMessage("advancements.nether.fast_travel.description", new Object[0]), (MinecraftKey) null, AdvancementFrameType.CHALLENGE, true, true, false).a(AdvancementRewards.a.a(100)).a("travelled", (CriterionInstance) CriterionTriggerNetherTravel.b.a(CriterionConditionDistance.a(CriterionConditionValue.FloatRange.b(7000.0F)))).a(consumer, "nether/fast_travel");
        Advancement advancement4 = Advancement.SerializedAdvancement.a().a(advancement1).a(Items.GHAST_TEAR, new ChatMessage("advancements.nether.uneasy_alliance.title", new Object[0]), new ChatMessage("advancements.nether.uneasy_alliance.description", new Object[0]), (MinecraftKey) null, AdvancementFrameType.CHALLENGE, true, true, false).a(AdvancementRewards.a.a(100)).a("killed_ghast", (CriterionInstance) CriterionTriggerKilled.b.a(CriterionConditionEntity.a.a().a(EntityTypes.GHAST).a(CriterionConditionLocation.a(DimensionManager.OVERWORLD)))).a(consumer, "nether/uneasy_alliance");
        Advancement advancement5 = Advancement.SerializedAdvancement.a().a(advancement2).a(Blocks.WITHER_SKELETON_SKULL, new ChatMessage("advancements.nether.get_wither_skull.title", new Object[0]), new ChatMessage("advancements.nether.get_wither_skull.description", new Object[0]), (MinecraftKey) null, AdvancementFrameType.TASK, true, true, false).a("wither_skull", (CriterionInstance) CriterionTriggerInventoryChanged.b.a(Blocks.WITHER_SKELETON_SKULL)).a(consumer, "nether/get_wither_skull");
        Advancement advancement6 = Advancement.SerializedAdvancement.a().a(advancement5).a(Items.NETHER_STAR, new ChatMessage("advancements.nether.summon_wither.title", new Object[0]), new ChatMessage("advancements.nether.summon_wither.description", new Object[0]), (MinecraftKey) null, AdvancementFrameType.TASK, true, true, false).a("summoned", (CriterionInstance) CriterionTriggerSummonedEntity.b.a(CriterionConditionEntity.a.a().a(EntityTypes.WITHER))).a(consumer, "nether/summon_wither");
        Advancement advancement7 = Advancement.SerializedAdvancement.a().a(advancement2).a(Items.BLAZE_ROD, new ChatMessage("advancements.nether.obtain_blaze_rod.title", new Object[0]), new ChatMessage("advancements.nether.obtain_blaze_rod.description", new Object[0]), (MinecraftKey) null, AdvancementFrameType.TASK, true, true, false).a("blaze_rod", (CriterionInstance) CriterionTriggerInventoryChanged.b.a(Items.BLAZE_ROD)).a(consumer, "nether/obtain_blaze_rod");
        Advancement advancement8 = Advancement.SerializedAdvancement.a().a(advancement6).a(Blocks.BEACON, new ChatMessage("advancements.nether.create_beacon.title", new Object[0]), new ChatMessage("advancements.nether.create_beacon.description", new Object[0]), (MinecraftKey) null, AdvancementFrameType.TASK, true, true, false).a("beacon", (CriterionInstance) CriterionTriggerConstructBeacon.b.a(CriterionConditionValue.IntegerRange.b(1))).a(consumer, "nether/create_beacon");
        Advancement advancement9 = Advancement.SerializedAdvancement.a().a(advancement8).a(Blocks.BEACON, new ChatMessage("advancements.nether.create_full_beacon.title", new Object[0]), new ChatMessage("advancements.nether.create_full_beacon.description", new Object[0]), (MinecraftKey) null, AdvancementFrameType.GOAL, true, true, false).a("beacon", (CriterionInstance) CriterionTriggerConstructBeacon.b.a(CriterionConditionValue.IntegerRange.a(4))).a(consumer, "nether/create_full_beacon");
        Advancement advancement10 = Advancement.SerializedAdvancement.a().a(advancement7).a(Items.POTION, new ChatMessage("advancements.nether.brew_potion.title", new Object[0]), new ChatMessage("advancements.nether.brew_potion.description", new Object[0]), (MinecraftKey) null, AdvancementFrameType.TASK, true, true, false).a("potion", (CriterionInstance) CriterionTriggerBrewedPotion.b.c()).a(consumer, "nether/brew_potion");
        Advancement advancement11 = Advancement.SerializedAdvancement.a().a(advancement10).a(Items.MILK_BUCKET, new ChatMessage("advancements.nether.all_potions.title", new Object[0]), new ChatMessage("advancements.nether.all_potions.description", new Object[0]), (MinecraftKey) null, AdvancementFrameType.CHALLENGE, true, true, false).a(AdvancementRewards.a.a(100)).a("all_effects", (CriterionInstance) CriterionTriggerEffectsChanged.b.a(CriterionConditionMobEffect.a().a(MobEffects.FASTER_MOVEMENT).a(MobEffects.SLOWER_MOVEMENT).a(MobEffects.INCREASE_DAMAGE).a(MobEffects.JUMP).a(MobEffects.REGENERATION).a(MobEffects.FIRE_RESISTANCE).a(MobEffects.WATER_BREATHING).a(MobEffects.INVISIBILITY).a(MobEffects.NIGHT_VISION).a(MobEffects.WEAKNESS).a(MobEffects.POISON).a(MobEffects.SLOW_FALLING).a(MobEffects.RESISTANCE))).a(consumer, "nether/all_potions");
        Advancement advancement12 = Advancement.SerializedAdvancement.a().a(advancement11).a(Items.BUCKET, new ChatMessage("advancements.nether.all_effects.title", new Object[0]), new ChatMessage("advancements.nether.all_effects.description", new Object[0]), (MinecraftKey) null, AdvancementFrameType.CHALLENGE, true, true, true).a(AdvancementRewards.a.a(1000)).a("all_effects", (CriterionInstance) CriterionTriggerEffectsChanged.b.a(CriterionConditionMobEffect.a().a(MobEffects.FASTER_MOVEMENT).a(MobEffects.SLOWER_MOVEMENT).a(MobEffects.INCREASE_DAMAGE).a(MobEffects.JUMP).a(MobEffects.REGENERATION).a(MobEffects.FIRE_RESISTANCE).a(MobEffects.WATER_BREATHING).a(MobEffects.INVISIBILITY).a(MobEffects.NIGHT_VISION).a(MobEffects.WEAKNESS).a(MobEffects.POISON).a(MobEffects.WITHER).a(MobEffects.FASTER_DIG).a(MobEffects.SLOWER_DIG).a(MobEffects.LEVITATION).a(MobEffects.GLOWING).a(MobEffects.ABSORBTION).a(MobEffects.HUNGER).a(MobEffects.CONFUSION).a(MobEffects.RESISTANCE).a(MobEffects.SLOW_FALLING).a(MobEffects.CONDUIT_POWER).a(MobEffects.DOLPHINS_GRACE))).a(consumer, "nether/all_effects");
    }
}
