package net.minecraft.server;

public class SoundEffects {

    public static final SoundEffect AMBIENT_CAVE;
    public static final SoundEffect AMBIENT_UNDERWATER_ENTER;
    public static final SoundEffect AMBIENT_UNDERWATER_EXIT;
    public static final SoundEffect AMBIENT_UNDERWATER_LOOP;
    public static final SoundEffect AMBIENT_UNDERWATER_LOOP_ADDITIONS;
    public static final SoundEffect AMBIENT_UNDERWATER_LOOP_ADDITIONS_RARE;
    public static final SoundEffect AMBIENT_UNDERWATER_LOOP_ADDITIONS_ULTRA_RARE;
    public static final SoundEffect BLOCK_ANVIL_BREAK;
    public static final SoundEffect BLOCK_ANVIL_DESTROY;
    public static final SoundEffect BLOCK_ANVIL_FALL;
    public static final SoundEffect BLOCK_ANVIL_HIT;
    public static final SoundEffect BLOCK_ANVIL_LAND;
    public static final SoundEffect BLOCK_ANVIL_PLACE;
    public static final SoundEffect BLOCK_ANVIL_STEP;
    public static final SoundEffect BLOCK_ANVIL_USE;
    public static final SoundEffect ITEM_ARMOR_EQUIP_CHAIN;
    public static final SoundEffect ITEM_ARMOR_EQUIP_DIAMOND;
    public static final SoundEffect ITEM_ARMOR_EQUIP_ELYTRA;
    public static final SoundEffect ITEM_ARMOR_EQUIP_GENERIC;
    public static final SoundEffect ITEM_ARMOR_EQUIP_GOLD;
    public static final SoundEffect ITEM_ARMOR_EQUIP_IRON;
    public static final SoundEffect ITEM_ARMOR_EQUIP_LEATHER;
    public static final SoundEffect ITEM_ARMOR_EQUIP_TURTLE;
    public static final SoundEffect ENTITY_ARMOR_STAND_BREAK;
    public static final SoundEffect ENTITY_ARMOR_STAND_FALL;
    public static final SoundEffect ENTITY_ARMOR_STAND_HIT;
    public static final SoundEffect ENTITY_ARMOR_STAND_PLACE;
    public static final SoundEffect ENTITY_ARROW_HIT;
    public static final SoundEffect ENTITY_ARROW_HIT_PLAYER;
    public static final SoundEffect ENTITY_ARROW_SHOOT;
    public static final SoundEffect ITEM_AXE_STRIP;
    public static final SoundEffect ENTITY_BAT_AMBIENT;
    public static final SoundEffect ENTITY_BAT_DEATH;
    public static final SoundEffect ENTITY_BAT_HURT;
    public static final SoundEffect ENTITY_BAT_LOOP;
    public static final SoundEffect ENTITY_BAT_TAKEOFF;
    public static final SoundEffect BLOCK_BEACON_ACTIVATE;
    public static final SoundEffect BLOCK_BEACON_AMBIENT;
    public static final SoundEffect BLOCK_BEACON_DEACTIVATE;
    public static final SoundEffect BLOCK_BEACON_POWER_SELECT;
    public static final SoundEffect ENTITY_BLAZE_AMBIENT;
    public static final SoundEffect ENTITY_BLAZE_BURN;
    public static final SoundEffect ENTITY_BLAZE_DEATH;
    public static final SoundEffect ENTITY_BLAZE_HURT;
    public static final SoundEffect ENTITY_BLAZE_SHOOT;
    public static final SoundEffect ENTITY_BOAT_PADDLE_LAND;
    public static final SoundEffect ENTITY_BOAT_PADDLE_WATER;
    public static final SoundEffect ENTITY_FISHING_BOBBER_RETRIEVE;
    public static final SoundEffect ENTITY_FISHING_BOBBER_SPLASH;
    public static final SoundEffect ENTITY_FISHING_BOBBER_THROW;
    public static final SoundEffect ITEM_BOTTLE_EMPTY;
    public static final SoundEffect ITEM_BOTTLE_FILL;
    public static final SoundEffect ITEM_BOTTLE_FILL_DRAGONBREATH;
    public static final SoundEffect BLOCK_BREWING_STAND_BREW;
    public static final SoundEffect BLOCK_BUBBLE_COLUMN_BUBBLE_POP;
    public static final SoundEffect BLOCK_BUBBLE_COLUMN_UPWARDS_AMBIENT;
    public static final SoundEffect BLOCK_BUBBLE_COLUMN_UPWARDS_INSIDE;
    public static final SoundEffect BLOCK_BUBBLE_COLUMN_WHIRLPOOL_AMBIENT;
    public static final SoundEffect BLOCK_BUBBLE_COLUMN_WHIRLPOOL_INSIDE;
    public static final SoundEffect ITEM_BUCKET_EMPTY;
    public static final SoundEffect ITEM_BUCKET_EMPTY_FISH;
    public static final SoundEffect ITEM_BUCKET_EMPTY_LAVA;
    public static final SoundEffect ITEM_BUCKET_FILL;
    public static final SoundEffect ITEM_BUCKET_FILL_FISH;
    public static final SoundEffect ITEM_BUCKET_FILL_LAVA;
    public static final SoundEffect ENTITY_CAT_AMBIENT;
    public static final SoundEffect ENTITY_CAT_DEATH;
    public static final SoundEffect ENTITY_CAT_HISS;
    public static final SoundEffect ENTITY_CAT_HURT;
    public static final SoundEffect ENTITY_CAT_PURR;
    public static final SoundEffect ENTITY_CAT_PURREOW;
    public static final SoundEffect BLOCK_CHEST_CLOSE;
    public static final SoundEffect BLOCK_CHEST_LOCKED;
    public static final SoundEffect BLOCK_CHEST_OPEN;
    public static final SoundEffect ENTITY_CHICKEN_AMBIENT;
    public static final SoundEffect ENTITY_CHICKEN_DEATH;
    public static final SoundEffect ENTITY_CHICKEN_EGG;
    public static final SoundEffect ENTITY_CHICKEN_HURT;
    public static final SoundEffect ENTITY_CHICKEN_STEP;
    public static final SoundEffect BLOCK_CHORUS_FLOWER_DEATH;
    public static final SoundEffect BLOCK_CHORUS_FLOWER_GROW;
    public static final SoundEffect ITEM_CHORUS_FRUIT_TELEPORT;
    public static final SoundEffect BLOCK_WOOL_BREAK;
    public static final SoundEffect BLOCK_WOOL_FALL;
    public static final SoundEffect BLOCK_WOOL_HIT;
    public static final SoundEffect BLOCK_WOOL_PLACE;
    public static final SoundEffect BLOCK_WOOL_STEP;
    public static final SoundEffect ENTITY_COD_AMBIENT;
    public static final SoundEffect ENTITY_COD_DEATH;
    public static final SoundEffect ENTITY_COD_FLOP;
    public static final SoundEffect ENTITY_COD_HURT;
    public static final SoundEffect BLOCK_COMPARATOR_CLICK;
    public static final SoundEffect BLOCK_CONDUIT_ACTIVATE;
    public static final SoundEffect BLOCK_CONDUIT_AMBIENT;
    public static final SoundEffect BLOCK_CONDUIT_AMBIENT_SHORT;
    public static final SoundEffect BLOCK_CONDUIT_ATTACK_TARGET;
    public static final SoundEffect BLOCK_CONDUIT_DEACTIVATE;
    public static final SoundEffect ENTITY_COW_AMBIENT;
    public static final SoundEffect ENTITY_COW_DEATH;
    public static final SoundEffect ENTITY_COW_HURT;
    public static final SoundEffect ENTITY_COW_MILK;
    public static final SoundEffect ENTITY_COW_STEP;
    public static final SoundEffect ENTITY_CREEPER_DEATH;
    public static final SoundEffect ENTITY_CREEPER_HURT;
    public static final SoundEffect ENTITY_CREEPER_PRIMED;
    public static final SoundEffect BLOCK_DISPENSER_DISPENSE;
    public static final SoundEffect BLOCK_DISPENSER_FAIL;
    public static final SoundEffect BLOCK_DISPENSER_LAUNCH;
    public static final SoundEffect ENTITY_DOLPHIN_AMBIENT;
    public static final SoundEffect ENTITY_DOLPHIN_AMBIENT_WATER;
    public static final SoundEffect ENTITY_DOLPHIN_ATTACK;
    public static final SoundEffect ENTITY_DOLPHIN_DEATH;
    public static final SoundEffect ENTITY_DOLPHIN_EAT;
    public static final SoundEffect ENTITY_DOLPHIN_HURT;
    public static final SoundEffect ENTITY_DOLPHIN_JUMP;
    public static final SoundEffect ENTITY_DOLPHIN_PLAY;
    public static final SoundEffect ENTITY_DOLPHIN_SPLASH;
    public static final SoundEffect ENTITY_DOLPHIN_SWIM;
    public static final SoundEffect ENTITY_DONKEY_AMBIENT;
    public static final SoundEffect ENTITY_DONKEY_ANGRY;
    public static final SoundEffect ENTITY_DONKEY_CHEST;
    public static final SoundEffect ENTITY_DONKEY_DEATH;
    public static final SoundEffect ENTITY_DONKEY_HURT;
    public static final SoundEffect ENTITY_DROWNED_AMBIENT;
    public static final SoundEffect ENTITY_DROWNED_AMBIENT_WATER;
    public static final SoundEffect ENTITY_DROWNED_DEATH;
    public static final SoundEffect ENTITY_DROWNED_DEATH_WATER;
    public static final SoundEffect ENTITY_DROWNED_HURT;
    public static final SoundEffect ENTITY_DROWNED_HURT_WATER;
    public static final SoundEffect ENTITY_DROWNED_SHOOT;
    public static final SoundEffect ENTITY_DROWNED_STEP;
    public static final SoundEffect ENTITY_DROWNED_SWIM;
    public static final SoundEffect ENTITY_EGG_THROW;
    public static final SoundEffect ENTITY_ELDER_GUARDIAN_AMBIENT;
    public static final SoundEffect ENTITY_ELDER_GUARDIAN_AMBIENT_LAND;
    public static final SoundEffect ENTITY_ELDER_GUARDIAN_CURSE;
    public static final SoundEffect ENTITY_ELDER_GUARDIAN_DEATH;
    public static final SoundEffect ENTITY_ELDER_GUARDIAN_DEATH_LAND;
    public static final SoundEffect ENTITY_ELDER_GUARDIAN_FLOP;
    public static final SoundEffect ENTITY_ELDER_GUARDIAN_HURT;
    public static final SoundEffect ENTITY_ELDER_GUARDIAN_HURT_LAND;
    public static final SoundEffect ITEM_ELYTRA_FLYING;
    public static final SoundEffect BLOCK_ENCHANTMENT_TABLE_USE;
    public static final SoundEffect BLOCK_ENDER_CHEST_CLOSE;
    public static final SoundEffect BLOCK_ENDER_CHEST_OPEN;
    public static final SoundEffect ENTITY_ENDER_DRAGON_AMBIENT;
    public static final SoundEffect ENTITY_ENDER_DRAGON_DEATH;
    public static final SoundEffect ENTITY_DRAGON_FIREBALL_EXPLODE;
    public static final SoundEffect ENTITY_ENDER_DRAGON_FLAP;
    public static final SoundEffect ENTITY_ENDER_DRAGON_GROWL;
    public static final SoundEffect ENTITY_ENDER_DRAGON_HURT;
    public static final SoundEffect ENTITY_ENDER_DRAGON_SHOOT;
    public static final SoundEffect ENTITY_ENDER_EYE_DEATH;
    public static final SoundEffect ENTITY_ENDER_EYE_LAUNCH;
    public static final SoundEffect ENTITY_ENDERMAN_AMBIENT;
    public static final SoundEffect ENTITY_ENDERMAN_DEATH;
    public static final SoundEffect ENTITY_ENDERMAN_HURT;
    public static final SoundEffect ENTITY_ENDERMAN_SCREAM;
    public static final SoundEffect ENTITY_ENDERMAN_STARE;
    public static final SoundEffect ENTITY_ENDERMAN_TELEPORT;
    public static final SoundEffect ENTITY_ENDERMITE_AMBIENT;
    public static final SoundEffect ENTITY_ENDERMITE_DEATH;
    public static final SoundEffect ENTITY_ENDERMITE_HURT;
    public static final SoundEffect ENTITY_ENDERMITE_STEP;
    public static final SoundEffect ENTITY_ENDER_PEARL_THROW;
    public static final SoundEffect BLOCK_END_GATEWAY_SPAWN;
    public static final SoundEffect BLOCK_END_PORTAL_FRAME_FILL;
    public static final SoundEffect BLOCK_END_PORTAL_SPAWN;
    public static final SoundEffect ENTITY_EVOKER_AMBIENT;
    public static final SoundEffect ENTITY_EVOKER_CAST_SPELL;
    public static final SoundEffect ENTITY_EVOKER_DEATH;
    public static final SoundEffect ENTITY_EVOKER_FANGS_ATTACK;
    public static final SoundEffect ENTITY_EVOKER_HURT;
    public static final SoundEffect ENTITY_EVOKER_PREPARE_ATTACK;
    public static final SoundEffect ENTITY_EVOKER_PREPARE_SUMMON;
    public static final SoundEffect ENTITY_EVOKER_PREPARE_WOLOLO;
    public static final SoundEffect ENTITY_EXPERIENCE_BOTTLE_THROW;
    public static final SoundEffect ENTITY_EXPERIENCE_ORB_PICKUP;
    public static final SoundEffect BLOCK_FENCE_GATE_CLOSE;
    public static final SoundEffect BLOCK_FENCE_GATE_OPEN;
    public static final SoundEffect ITEM_FIRECHARGE_USE;
    public static final SoundEffect ENTITY_FIREWORK_ROCKET_BLAST;
    public static final SoundEffect ENTITY_FIREWORK_ROCKET_BLAST_FAR;
    public static final SoundEffect ENTITY_FIREWORK_ROCKET_LARGE_BLAST;
    public static final SoundEffect ENTITY_FIREWORK_ROCKET_LARGE_BLAST_FAR;
    public static final SoundEffect ENTITY_FIREWORK_ROCKET_LAUNCH;
    public static final SoundEffect ENTITY_FIREWORK_ROCKET_SHOOT;
    public static final SoundEffect ENTITY_FIREWORK_ROCKET_TWINKLE;
    public static final SoundEffect ENTITY_FIREWORK_ROCKET_TWINKLE_FAR;
    public static final SoundEffect BLOCK_FIRE_AMBIENT;
    public static final SoundEffect BLOCK_FIRE_EXTINGUISH;
    public static final SoundEffect ENTITY_FISH_SWIM;
    public static final SoundEffect ITEM_FLINTANDSTEEL_USE;
    public static final SoundEffect BLOCK_FURNACE_FIRE_CRACKLE;
    public static final SoundEffect ENTITY_GENERIC_BIG_FALL;
    public static final SoundEffect ENTITY_GENERIC_BURN;
    public static final SoundEffect ENTITY_GENERIC_DEATH;
    public static final SoundEffect ENTITY_GENERIC_DRINK;
    public static final SoundEffect ENTITY_GENERIC_EAT;
    public static final SoundEffect ENTITY_GENERIC_EXPLODE;
    public static final SoundEffect ENTITY_GENERIC_EXTINGUISH_FIRE;
    public static final SoundEffect ENTITY_GENERIC_HURT;
    public static final SoundEffect ENTITY_GENERIC_SMALL_FALL;
    public static final SoundEffect ENTITY_GENERIC_SPLASH;
    public static final SoundEffect ENTITY_GENERIC_SWIM;
    public static final SoundEffect ENTITY_GHAST_AMBIENT;
    public static final SoundEffect ENTITY_GHAST_DEATH;
    public static final SoundEffect ENTITY_GHAST_HURT;
    public static final SoundEffect ENTITY_GHAST_SCREAM;
    public static final SoundEffect ENTITY_GHAST_SHOOT;
    public static final SoundEffect ENTITY_GHAST_WARN;
    public static final SoundEffect BLOCK_GLASS_BREAK;
    public static final SoundEffect BLOCK_GLASS_FALL;
    public static final SoundEffect BLOCK_GLASS_HIT;
    public static final SoundEffect BLOCK_GLASS_PLACE;
    public static final SoundEffect BLOCK_GLASS_STEP;
    public static final SoundEffect BLOCK_GRASS_BREAK;
    public static final SoundEffect BLOCK_GRASS_FALL;
    public static final SoundEffect BLOCK_GRASS_HIT;
    public static final SoundEffect BLOCK_GRASS_PLACE;
    public static final SoundEffect BLOCK_GRASS_STEP;
    public static final SoundEffect BLOCK_WET_GRASS_BREAK;
    public static final SoundEffect BLOCK_WET_GRASS_FALL;
    public static final SoundEffect BLOCK_WET_GRASS_HIT;
    public static final SoundEffect BLOCK_WET_GRASS_PLACE;
    public static final SoundEffect BLOCK_WET_GRASS_STEP;
    public static final SoundEffect BLOCK_CORAL_BLOCK_BREAK;
    public static final SoundEffect BLOCK_CORAL_BLOCK_FALL;
    public static final SoundEffect BLOCK_CORAL_BLOCK_HIT;
    public static final SoundEffect BLOCK_CORAL_BLOCK_PLACE;
    public static final SoundEffect BLOCK_CORAL_BLOCK_STEP;
    public static final SoundEffect BLOCK_GRAVEL_BREAK;
    public static final SoundEffect BLOCK_GRAVEL_FALL;
    public static final SoundEffect BLOCK_GRAVEL_HIT;
    public static final SoundEffect BLOCK_GRAVEL_PLACE;
    public static final SoundEffect BLOCK_GRAVEL_STEP;
    public static final SoundEffect ENTITY_GUARDIAN_AMBIENT;
    public static final SoundEffect ENTITY_GUARDIAN_AMBIENT_LAND;
    public static final SoundEffect ENTITY_GUARDIAN_ATTACK;
    public static final SoundEffect ENTITY_GUARDIAN_DEATH;
    public static final SoundEffect ENTITY_GUARDIAN_DEATH_LAND;
    public static final SoundEffect ENTITY_GUARDIAN_FLOP;
    public static final SoundEffect ENTITY_GUARDIAN_HURT;
    public static final SoundEffect ENTITY_GUARDIAN_HURT_LAND;
    public static final SoundEffect ITEM_HOE_TILL;
    public static final SoundEffect ENTITY_HORSE_AMBIENT;
    public static final SoundEffect ENTITY_HORSE_ANGRY;
    public static final SoundEffect ENTITY_HORSE_ARMOR;
    public static final SoundEffect ENTITY_HORSE_BREATHE;
    public static final SoundEffect ENTITY_HORSE_DEATH;
    public static final SoundEffect ENTITY_HORSE_EAT;
    public static final SoundEffect ENTITY_HORSE_GALLOP;
    public static final SoundEffect ENTITY_HORSE_HURT;
    public static final SoundEffect ENTITY_HORSE_JUMP;
    public static final SoundEffect ENTITY_HORSE_LAND;
    public static final SoundEffect ENTITY_HORSE_SADDLE;
    public static final SoundEffect ENTITY_HORSE_STEP;
    public static final SoundEffect ENTITY_HORSE_STEP_WOOD;
    public static final SoundEffect ENTITY_HOSTILE_BIG_FALL;
    public static final SoundEffect ENTITY_HOSTILE_DEATH;
    public static final SoundEffect ENTITY_HOSTILE_HURT;
    public static final SoundEffect ENTITY_HOSTILE_SMALL_FALL;
    public static final SoundEffect ENTITY_HOSTILE_SPLASH;
    public static final SoundEffect ENTITY_HOSTILE_SWIM;
    public static final SoundEffect ENTITY_HUSK_AMBIENT;
    public static final SoundEffect ENTITY_HUSK_CONVERTED_TO_ZOMBIE;
    public static final SoundEffect ENTITY_HUSK_DEATH;
    public static final SoundEffect ENTITY_HUSK_HURT;
    public static final SoundEffect ENTITY_HUSK_STEP;
    public static final SoundEffect ENTITY_ILLUSIONER_AMBIENT;
    public static final SoundEffect ENTITY_ILLUSIONER_CAST_SPELL;
    public static final SoundEffect ENTITY_ILLUSIONER_DEATH;
    public static final SoundEffect ENTITY_ILLUSIONER_HURT;
    public static final SoundEffect ENTITY_ILLUSIONER_MIRROR_MOVE;
    public static final SoundEffect ENTITY_ILLUSIONER_PREPARE_BLINDNESS;
    public static final SoundEffect ENTITY_ILLUSIONER_PREPARE_MIRROR;
    public static final SoundEffect BLOCK_IRON_DOOR_CLOSE;
    public static final SoundEffect BLOCK_IRON_DOOR_OPEN;
    public static final SoundEffect ENTITY_IRON_GOLEM_ATTACK;
    public static final SoundEffect ENTITY_IRON_GOLEM_DEATH;
    public static final SoundEffect ENTITY_IRON_GOLEM_HURT;
    public static final SoundEffect ENTITY_IRON_GOLEM_STEP;
    public static final SoundEffect BLOCK_IRON_TRAPDOOR_CLOSE;
    public static final SoundEffect BLOCK_IRON_TRAPDOOR_OPEN;
    public static final SoundEffect ENTITY_ITEM_FRAME_ADD_ITEM;
    public static final SoundEffect ENTITY_ITEM_FRAME_BREAK;
    public static final SoundEffect ENTITY_ITEM_FRAME_PLACE;
    public static final SoundEffect ENTITY_ITEM_FRAME_REMOVE_ITEM;
    public static final SoundEffect ENTITY_ITEM_FRAME_ROTATE_ITEM;
    public static final SoundEffect ENTITY_ITEM_BREAK;
    public static final SoundEffect ENTITY_ITEM_PICKUP;
    public static final SoundEffect BLOCK_LADDER_BREAK;
    public static final SoundEffect BLOCK_LADDER_FALL;
    public static final SoundEffect BLOCK_LADDER_HIT;
    public static final SoundEffect BLOCK_LADDER_PLACE;
    public static final SoundEffect BLOCK_LADDER_STEP;
    public static final SoundEffect BLOCK_LAVA_AMBIENT;
    public static final SoundEffect BLOCK_LAVA_EXTINGUISH;
    public static final SoundEffect BLOCK_LAVA_POP;
    public static final SoundEffect ENTITY_LEASH_KNOT_BREAK;
    public static final SoundEffect ENTITY_LEASH_KNOT_PLACE;
    public static final SoundEffect BLOCK_LEVER_CLICK;
    public static final SoundEffect ENTITY_LIGHTNING_BOLT_IMPACT;
    public static final SoundEffect ENTITY_LIGHTNING_BOLT_THUNDER;
    public static final SoundEffect ENTITY_LINGERING_POTION_THROW;
    public static final SoundEffect ENTITY_LLAMA_AMBIENT;
    public static final SoundEffect ENTITY_LLAMA_ANGRY;
    public static final SoundEffect ENTITY_LLAMA_CHEST;
    public static final SoundEffect ENTITY_LLAMA_DEATH;
    public static final SoundEffect ENTITY_LLAMA_EAT;
    public static final SoundEffect ENTITY_LLAMA_HURT;
    public static final SoundEffect ENTITY_LLAMA_SPIT;
    public static final SoundEffect ENTITY_LLAMA_STEP;
    public static final SoundEffect ENTITY_LLAMA_SWAG;
    public static final SoundEffect ENTITY_MAGMA_CUBE_DEATH;
    public static final SoundEffect ENTITY_MAGMA_CUBE_HURT;
    public static final SoundEffect ENTITY_MAGMA_CUBE_JUMP;
    public static final SoundEffect ENTITY_MAGMA_CUBE_SQUISH;
    public static final SoundEffect BLOCK_METAL_BREAK;
    public static final SoundEffect BLOCK_METAL_FALL;
    public static final SoundEffect BLOCK_METAL_HIT;
    public static final SoundEffect BLOCK_METAL_PLACE;
    public static final SoundEffect BLOCK_METAL_PRESSURE_PLATE_CLICK_OFF;
    public static final SoundEffect BLOCK_METAL_PRESSURE_PLATE_CLICK_ON;
    public static final SoundEffect BLOCK_METAL_STEP;
    public static final SoundEffect ENTITY_MINECART_INSIDE;
    public static final SoundEffect ENTITY_MINECART_RIDING;
    public static final SoundEffect ENTITY_MOOSHROOM_SHEAR;
    public static final SoundEffect ENTITY_MULE_AMBIENT;
    public static final SoundEffect ENTITY_MULE_CHEST;
    public static final SoundEffect ENTITY_MULE_DEATH;
    public static final SoundEffect ENTITY_MULE_HURT;
    public static final SoundEffect MUSIC_CREATIVE;
    public static final SoundEffect MUSIC_CREDITS;
    public static final SoundEffect MUSIC_DRAGON;
    public static final SoundEffect MUSIC_END;
    public static final SoundEffect MUSIC_GAME;
    public static final SoundEffect MUSIC_MENU;
    public static final SoundEffect MUSIC_NETHER;
    public static final SoundEffect MUSIC_UNDER_WATER;
    public static final SoundEffect BLOCK_NOTE_BLOCK_BASEDRUM;
    public static final SoundEffect BLOCK_NOTE_BLOCK_BASS;
    public static final SoundEffect BLOCK_NOTE_BLOCK_BELL;
    public static final SoundEffect BLOCK_NOTE_BLOCK_CHIME;
    public static final SoundEffect BLOCK_NOTE_BLOCK_FLUTE;
    public static final SoundEffect BLOCK_NOTE_BLOCK_GUITAR;
    public static final SoundEffect BLOCK_NOTE_BLOCK_HARP;
    public static final SoundEffect BLOCK_NOTE_BLOCK_HAT;
    public static final SoundEffect BLOCK_NOTE_BLOCK_PLING;
    public static final SoundEffect BLOCK_NOTE_BLOCK_SNARE;
    public static final SoundEffect BLOCK_NOTE_BLOCK_XYLOPHONE;
    public static final SoundEffect ENTITY_PAINTING_BREAK;
    public static final SoundEffect ENTITY_PAINTING_PLACE;
    public static final SoundEffect ENTITY_PARROT_AMBIENT;
    public static final SoundEffect ENTITY_PARROT_DEATH;
    public static final SoundEffect ENTITY_PARROT_EAT;
    public static final SoundEffect ENTITY_PARROT_FLY;
    public static final SoundEffect ENTITY_PARROT_HURT;
    public static final SoundEffect ENTITY_PARROT_IMITATE_BLAZE;
    public static final SoundEffect ENTITY_PARROT_IMITATE_CREEPER;
    public static final SoundEffect ENTITY_PARROT_IMITATE_DROWNED;
    public static final SoundEffect ENTITY_PARROT_IMITATE_ELDER_GUARDIAN;
    public static final SoundEffect ENTITY_PARROT_IMITATE_ENDER_DRAGON;
    public static final SoundEffect ENTITY_PARROT_IMITATE_ENDERMAN;
    public static final SoundEffect ENTITY_PARROT_IMITATE_ENDERMITE;
    public static final SoundEffect ENTITY_PARROT_IMITATE_EVOKER;
    public static final SoundEffect ENTITY_PARROT_IMITATE_GHAST;
    public static final SoundEffect ENTITY_PARROT_IMITATE_HUSK;
    public static final SoundEffect ENTITY_PARROT_IMITATE_ILLUSIONER;
    public static final SoundEffect ENTITY_PARROT_IMITATE_MAGMA_CUBE;
    public static final SoundEffect ENTITY_PARROT_IMITATE_PHANTOM;
    public static final SoundEffect ENTITY_PARROT_IMITATE_POLAR_BEAR;
    public static final SoundEffect ENTITY_PARROT_IMITATE_SHULKER;
    public static final SoundEffect ENTITY_PARROT_IMITATE_SILVERFISH;
    public static final SoundEffect ENTITY_PARROT_IMITATE_SKELETON;
    public static final SoundEffect ENTITY_PARROT_IMITATE_SLIME;
    public static final SoundEffect ENTITY_PARROT_IMITATE_SPIDER;
    public static final SoundEffect ENTITY_PARROT_IMITATE_STRAY;
    public static final SoundEffect ENTITY_PARROT_IMITATE_VEX;
    public static final SoundEffect ENTITY_PARROT_IMITATE_VINDICATOR;
    public static final SoundEffect ENTITY_PARROT_IMITATE_WITCH;
    public static final SoundEffect ENTITY_PARROT_IMITATE_WITHER;
    public static final SoundEffect ENTITY_PARROT_IMITATE_WITHER_SKELETON;
    public static final SoundEffect ENTITY_PARROT_IMITATE_WOLF;
    public static final SoundEffect ENTITY_PARROT_IMITATE_ZOMBIE;
    public static final SoundEffect ENTITY_PARROT_IMITATE_ZOMBIE_PIGMAN;
    public static final SoundEffect ENTITY_PARROT_IMITATE_ZOMBIE_VILLAGER;
    public static final SoundEffect ENTITY_PARROT_STEP;
    public static final SoundEffect ENTITY_PHANTOM_AMBIENT;
    public static final SoundEffect ENTITY_PHANTOM_BITE;
    public static final SoundEffect ENTITY_PHANTOM_DEATH;
    public static final SoundEffect ENTITY_PHANTOM_FLAP;
    public static final SoundEffect ENTITY_PHANTOM_HURT;
    public static final SoundEffect ENTITY_PHANTOM_SWOOP;
    public static final SoundEffect ENTITY_PIG_AMBIENT;
    public static final SoundEffect ENTITY_PIG_DEATH;
    public static final SoundEffect ENTITY_PIG_HURT;
    public static final SoundEffect ENTITY_PIG_SADDLE;
    public static final SoundEffect ENTITY_PIG_STEP;
    public static final SoundEffect BLOCK_PISTON_CONTRACT;
    public static final SoundEffect BLOCK_PISTON_EXTEND;
    public static final SoundEffect ENTITY_PLAYER_ATTACK_CRIT;
    public static final SoundEffect ENTITY_PLAYER_ATTACK_KNOCKBACK;
    public static final SoundEffect ENTITY_PLAYER_ATTACK_NODAMAGE;
    public static final SoundEffect ENTITY_PLAYER_ATTACK_STRONG;
    public static final SoundEffect ENTITY_PLAYER_ATTACK_SWEEP;
    public static final SoundEffect ENTITY_PLAYER_ATTACK_WEAK;
    public static final SoundEffect ENTITY_PLAYER_BIG_FALL;
    public static final SoundEffect ENTITY_PLAYER_BREATH;
    public static final SoundEffect ENTITY_PLAYER_BURP;
    public static final SoundEffect ENTITY_PLAYER_DEATH;
    public static final SoundEffect ENTITY_PLAYER_HURT;
    public static final SoundEffect ENTITY_PLAYER_HURT_DROWN;
    public static final SoundEffect ENTITY_PLAYER_HURT_ON_FIRE;
    public static final SoundEffect ENTITY_PLAYER_LEVELUP;
    public static final SoundEffect ENTITY_PLAYER_SMALL_FALL;
    public static final SoundEffect ENTITY_PLAYER_SPLASH;
    public static final SoundEffect ENTITY_PLAYER_SPLASH_HIGH_SPEED;
    public static final SoundEffect ENTITY_PLAYER_SWIM;
    public static final SoundEffect ENTITY_POLAR_BEAR_AMBIENT;
    public static final SoundEffect ENTITY_POLAR_BEAR_AMBIENT_BABY;
    public static final SoundEffect ENTITY_POLAR_BEAR_DEATH;
    public static final SoundEffect ENTITY_POLAR_BEAR_HURT;
    public static final SoundEffect ENTITY_POLAR_BEAR_STEP;
    public static final SoundEffect ENTITY_POLAR_BEAR_WARNING;
    public static final SoundEffect BLOCK_PORTAL_AMBIENT;
    public static final SoundEffect BLOCK_PORTAL_TRAVEL;
    public static final SoundEffect BLOCK_PORTAL_TRIGGER;
    public static final SoundEffect ENTITY_PUFFER_FISH_AMBIENT;
    public static final SoundEffect ENTITY_PUFFER_FISH_BLOW_OUT;
    public static final SoundEffect ENTITY_PUFFER_FISH_BLOW_UP;
    public static final SoundEffect ENTITY_PUFFER_FISH_DEATH;
    public static final SoundEffect ENTITY_PUFFER_FISH_FLOP;
    public static final SoundEffect ENTITY_PUFFER_FISH_HURT;
    public static final SoundEffect ENTITY_PUFFER_FISH_STING;
    public static final SoundEffect BLOCK_PUMPKIN_CARVE;
    public static final SoundEffect ENTITY_RABBIT_AMBIENT;
    public static final SoundEffect ENTITY_RABBIT_ATTACK;
    public static final SoundEffect ENTITY_RABBIT_DEATH;
    public static final SoundEffect ENTITY_RABBIT_HURT;
    public static final SoundEffect ENTITY_RABBIT_JUMP;
    public static final SoundEffect MUSIC_DISC_11;
    public static final SoundEffect MUSIC_DISC_13;
    public static final SoundEffect MUSIC_DISC_BLOCKS;
    public static final SoundEffect MUSIC_DISC_CAT;
    public static final SoundEffect MUSIC_DISC_CHIRP;
    public static final SoundEffect MUSIC_DISC_FAR;
    public static final SoundEffect MUSIC_DISC_MALL;
    public static final SoundEffect MUSIC_DISC_MELLOHI;
    public static final SoundEffect MUSIC_DISC_STAL;
    public static final SoundEffect MUSIC_DISC_STRAD;
    public static final SoundEffect MUSIC_DISC_WAIT;
    public static final SoundEffect MUSIC_DISC_WARD;
    public static final SoundEffect BLOCK_REDSTONE_TORCH_BURNOUT;
    public static final SoundEffect ENTITY_SALMON_AMBIENT;
    public static final SoundEffect ENTITY_SALMON_DEATH;
    public static final SoundEffect ENTITY_SALMON_FLOP;
    public static final SoundEffect ENTITY_SALMON_HURT;
    public static final SoundEffect BLOCK_SAND_BREAK;
    public static final SoundEffect BLOCK_SAND_FALL;
    public static final SoundEffect BLOCK_SAND_HIT;
    public static final SoundEffect BLOCK_SAND_PLACE;
    public static final SoundEffect BLOCK_SAND_STEP;
    public static final SoundEffect ENTITY_SHEEP_AMBIENT;
    public static final SoundEffect ENTITY_SHEEP_DEATH;
    public static final SoundEffect ENTITY_SHEEP_HURT;
    public static final SoundEffect ENTITY_SHEEP_SHEAR;
    public static final SoundEffect ENTITY_SHEEP_STEP;
    public static final SoundEffect ITEM_SHIELD_BLOCK;
    public static final SoundEffect ITEM_SHIELD_BREAK;
    public static final SoundEffect ITEM_SHOVEL_FLATTEN;
    public static final SoundEffect ENTITY_SHULKER_AMBIENT;
    public static final SoundEffect BLOCK_SHULKER_BOX_CLOSE;
    public static final SoundEffect BLOCK_SHULKER_BOX_OPEN;
    public static final SoundEffect ENTITY_SHULKER_BULLET_HIT;
    public static final SoundEffect ENTITY_SHULKER_BULLET_HURT;
    public static final SoundEffect ENTITY_SHULKER_CLOSE;
    public static final SoundEffect ENTITY_SHULKER_DEATH;
    public static final SoundEffect ENTITY_SHULKER_HURT;
    public static final SoundEffect ENTITY_SHULKER_HURT_CLOSED;
    public static final SoundEffect ENTITY_SHULKER_OPEN;
    public static final SoundEffect ENTITY_SHULKER_SHOOT;
    public static final SoundEffect ENTITY_SHULKER_TELEPORT;
    public static final SoundEffect ENTITY_SILVERFISH_AMBIENT;
    public static final SoundEffect ENTITY_SILVERFISH_DEATH;
    public static final SoundEffect ENTITY_SILVERFISH_HURT;
    public static final SoundEffect ENTITY_SILVERFISH_STEP;
    public static final SoundEffect ENTITY_SKELETON_AMBIENT;
    public static final SoundEffect ENTITY_SKELETON_DEATH;
    public static final SoundEffect ENTITY_SKELETON_HORSE_AMBIENT;
    public static final SoundEffect ENTITY_SKELETON_HORSE_DEATH;
    public static final SoundEffect ENTITY_SKELETON_HORSE_HURT;
    public static final SoundEffect ENTITY_SKELETON_HORSE_SWIM;
    public static final SoundEffect ENTITY_SKELETON_HORSE_AMBIENT_WATER;
    public static final SoundEffect ENTITY_SKELETON_HORSE_GALLOP_WATER;
    public static final SoundEffect ENTITY_SKELETON_HORSE_JUMP_WATER;
    public static final SoundEffect ENTITY_SKELETON_HORSE_STEP_WATER;
    public static final SoundEffect ENTITY_SKELETON_HURT;
    public static final SoundEffect ENTITY_SKELETON_SHOOT;
    public static final SoundEffect ENTITY_SKELETON_STEP;
    public static final SoundEffect ENTITY_SLIME_ATTACK;
    public static final SoundEffect ENTITY_SLIME_DEATH;
    public static final SoundEffect ENTITY_SLIME_HURT;
    public static final SoundEffect ENTITY_SLIME_JUMP;
    public static final SoundEffect ENTITY_SLIME_SQUISH;
    public static final SoundEffect BLOCK_SLIME_BLOCK_BREAK;
    public static final SoundEffect BLOCK_SLIME_BLOCK_FALL;
    public static final SoundEffect BLOCK_SLIME_BLOCK_HIT;
    public static final SoundEffect BLOCK_SLIME_BLOCK_PLACE;
    public static final SoundEffect BLOCK_SLIME_BLOCK_STEP;
    public static final SoundEffect ENTITY_MAGMA_CUBE_DEATH_SMALL;
    public static final SoundEffect ENTITY_MAGMA_CUBE_HURT_SMALL;
    public static final SoundEffect ENTITY_MAGMA_CUBE_SQUISH_SMALL;
    public static final SoundEffect ENTITY_SLIME_DEATH_SMALL;
    public static final SoundEffect ENTITY_SLIME_HURT_SMALL;
    public static final SoundEffect ENTITY_SLIME_JUMP_SMALL;
    public static final SoundEffect ENTITY_SLIME_SQUISH_SMALL;
    public static final SoundEffect ENTITY_SNOWBALL_THROW;
    public static final SoundEffect BLOCK_SNOW_BREAK;
    public static final SoundEffect BLOCK_SNOW_FALL;
    public static final SoundEffect ENTITY_SNOW_GOLEM_AMBIENT;
    public static final SoundEffect ENTITY_SNOW_GOLEM_DEATH;
    public static final SoundEffect ENTITY_SNOW_GOLEM_HURT;
    public static final SoundEffect ENTITY_SNOW_GOLEM_SHOOT;
    public static final SoundEffect BLOCK_SNOW_HIT;
    public static final SoundEffect BLOCK_SNOW_PLACE;
    public static final SoundEffect BLOCK_SNOW_STEP;
    public static final SoundEffect ENTITY_SPIDER_AMBIENT;
    public static final SoundEffect ENTITY_SPIDER_DEATH;
    public static final SoundEffect ENTITY_SPIDER_HURT;
    public static final SoundEffect ENTITY_SPIDER_STEP;
    public static final SoundEffect ENTITY_SPLASH_POTION_BREAK;
    public static final SoundEffect ENTITY_SPLASH_POTION_THROW;
    public static final SoundEffect ENTITY_SQUID_AMBIENT;
    public static final SoundEffect ENTITY_SQUID_DEATH;
    public static final SoundEffect ENTITY_SQUID_HURT;
    public static final SoundEffect ENTITY_SQUID_SQUIRT;
    public static final SoundEffect BLOCK_STONE_BREAK;
    public static final SoundEffect BLOCK_STONE_BUTTON_CLICK_OFF;
    public static final SoundEffect BLOCK_STONE_BUTTON_CLICK_ON;
    public static final SoundEffect BLOCK_STONE_FALL;
    public static final SoundEffect BLOCK_STONE_HIT;
    public static final SoundEffect BLOCK_STONE_PLACE;
    public static final SoundEffect BLOCK_STONE_PRESSURE_PLATE_CLICK_OFF;
    public static final SoundEffect BLOCK_STONE_PRESSURE_PLATE_CLICK_ON;
    public static final SoundEffect BLOCK_STONE_STEP;
    public static final SoundEffect ENTITY_STRAY_AMBIENT;
    public static final SoundEffect ENTITY_STRAY_DEATH;
    public static final SoundEffect ENTITY_STRAY_HURT;
    public static final SoundEffect ENTITY_STRAY_STEP;
    public static final SoundEffect ENCHANT_THORNS_HIT;
    public static final SoundEffect ENTITY_TNT_PRIMED;
    public static final SoundEffect ITEM_TOTEM_USE;
    public static final SoundEffect ITEM_TRIDENT_HIT;
    public static final SoundEffect ITEM_TRIDENT_HIT_GROUND;
    public static final SoundEffect ITEM_TRIDENT_RETURN;
    public static final SoundEffect ITEM_TRIDENT_RIPTIDE_1;
    public static final SoundEffect ITEM_TRIDENT_RIPTIDE_2;
    public static final SoundEffect ITEM_TRIDENT_RIPTIDE_3;
    public static final SoundEffect ITEM_TRIDENT_THROW;
    public static final SoundEffect ITEM_TRIDENT_THUNDER;
    public static final SoundEffect BLOCK_TRIPWIRE_ATTACH;
    public static final SoundEffect BLOCK_TRIPWIRE_CLICK_OFF;
    public static final SoundEffect BLOCK_TRIPWIRE_CLICK_ON;
    public static final SoundEffect BLOCK_TRIPWIRE_DETACH;
    public static final SoundEffect ENTITY_TROPICAL_FISH_AMBIENT;
    public static final SoundEffect ENTITY_TROPICAL_FISH_DEATH;
    public static final SoundEffect ENTITY_TROPICAL_FISH_FLOP;
    public static final SoundEffect ENTITY_TROPICAL_FISH_HURT;
    public static final SoundEffect ENTITY_TURTLE_AMBIENT_LAND;
    public static final SoundEffect ENTITY_TURTLE_DEATH;
    public static final SoundEffect ENTITY_TURTLE_DEATH_BABY;
    public static final SoundEffect ENTITY_TURTLE_EGG_BREAK;
    public static final SoundEffect ENTITY_TURTLE_EGG_CRACK;
    public static final SoundEffect ENTITY_TURTLE_EGG_HATCH;
    public static final SoundEffect ENTITY_TURTLE_HURT;
    public static final SoundEffect ENTITY_TURTLE_HURT_BABY;
    public static final SoundEffect ENTITY_TURTLE_LAY_EGG;
    public static final SoundEffect ENTITY_TURTLE_SHAMBLE;
    public static final SoundEffect ENTITY_TURTLE_SHAMBLE_BABY;
    public static final SoundEffect ENTITY_TURTLE_SWIM;
    public static final SoundEffect UI_BUTTON_CLICK;
    public static final SoundEffect UI_TOAST_CHALLENGE_COMPLETE;
    public static final SoundEffect UI_TOAST_IN;
    public static final SoundEffect UI_TOAST_OUT;
    public static final SoundEffect ENTITY_VEX_AMBIENT;
    public static final SoundEffect ENTITY_VEX_CHARGE;
    public static final SoundEffect ENTITY_VEX_DEATH;
    public static final SoundEffect ENTITY_VEX_HURT;
    public static final SoundEffect ENTITY_VILLAGER_AMBIENT;
    public static final SoundEffect ENTITY_VILLAGER_DEATH;
    public static final SoundEffect ENTITY_VILLAGER_HURT;
    public static final SoundEffect ENTITY_VILLAGER_NO;
    public static final SoundEffect ENTITY_VILLAGER_TRADE;
    public static final SoundEffect ENTITY_VILLAGER_YES;
    public static final SoundEffect ENTITY_VINDICATOR_AMBIENT;
    public static final SoundEffect ENTITY_VINDICATOR_DEATH;
    public static final SoundEffect ENTITY_VINDICATOR_HURT;
    public static final SoundEffect BLOCK_LILY_PAD_PLACE;
    public static final SoundEffect BLOCK_WATER_AMBIENT;
    public static final SoundEffect WEATHER_RAIN;
    public static final SoundEffect WEATHER_RAIN_ABOVE;
    public static final SoundEffect ENTITY_WITCH_AMBIENT;
    public static final SoundEffect ENTITY_WITCH_DEATH;
    public static final SoundEffect ENTITY_WITCH_DRINK;
    public static final SoundEffect ENTITY_WITCH_HURT;
    public static final SoundEffect ENTITY_WITCH_THROW;
    public static final SoundEffect ENTITY_WITHER_AMBIENT;
    public static final SoundEffect ENTITY_WITHER_BREAK_BLOCK;
    public static final SoundEffect ENTITY_WITHER_DEATH;
    public static final SoundEffect ENTITY_WITHER_HURT;
    public static final SoundEffect ENTITY_WITHER_SHOOT;
    public static final SoundEffect ENTITY_WITHER_SKELETON_AMBIENT;
    public static final SoundEffect ENTITY_WITHER_SKELETON_DEATH;
    public static final SoundEffect ENTITY_WITHER_SKELETON_HURT;
    public static final SoundEffect ENTITY_WITHER_SKELETON_STEP;
    public static final SoundEffect ENTITY_WITHER_SPAWN;
    public static final SoundEffect ENTITY_WOLF_AMBIENT;
    public static final SoundEffect ENTITY_WOLF_DEATH;
    public static final SoundEffect ENTITY_WOLF_GROWL;
    public static final SoundEffect ENTITY_WOLF_HOWL;
    public static final SoundEffect ENTITY_WOLF_HURT;
    public static final SoundEffect ENTITY_WOLF_PANT;
    public static final SoundEffect ENTITY_WOLF_SHAKE;
    public static final SoundEffect ENTITY_WOLF_STEP;
    public static final SoundEffect ENTITY_WOLF_WHINE;
    public static final SoundEffect BLOCK_WOODEN_DOOR_CLOSE;
    public static final SoundEffect BLOCK_WOODEN_DOOR_OPEN;
    public static final SoundEffect BLOCK_WOODEN_TRAPDOOR_CLOSE;
    public static final SoundEffect BLOCK_WOODEN_TRAPDOOR_OPEN;
    public static final SoundEffect BLOCK_WOOD_BREAK;
    public static final SoundEffect BLOCK_WOODEN_BUTTON_CLICK_OFF;
    public static final SoundEffect BLOCK_WOODEN_BUTTON_CLICK_ON;
    public static final SoundEffect BLOCK_WOOD_FALL;
    public static final SoundEffect BLOCK_WOOD_HIT;
    public static final SoundEffect BLOCK_WOOD_PLACE;
    public static final SoundEffect BLOCK_WOODEN_PRESSURE_PLATE_CLICK_OFF;
    public static final SoundEffect BLOCK_WOODEN_PRESSURE_PLATE_CLICK_ON;
    public static final SoundEffect BLOCK_WOOD_STEP;
    public static final SoundEffect ENTITY_ZOMBIE_AMBIENT;
    public static final SoundEffect ENTITY_ZOMBIE_ATTACK_WOODEN_DOOR;
    public static final SoundEffect ENTITY_ZOMBIE_ATTACK_IRON_DOOR;
    public static final SoundEffect ENTITY_ZOMBIE_BREAK_WOODEN_DOOR;
    public static final SoundEffect ENTITY_ZOMBIE_CONVERTED_TO_DROWNED;
    public static final SoundEffect ENTITY_ZOMBIE_DEATH;
    public static final SoundEffect ENTITY_ZOMBIE_DESTROY_EGG;
    public static final SoundEffect ENTITY_ZOMBIE_HORSE_AMBIENT;
    public static final SoundEffect ENTITY_ZOMBIE_HORSE_DEATH;
    public static final SoundEffect ENTITY_ZOMBIE_HORSE_HURT;
    public static final SoundEffect ENTITY_ZOMBIE_HURT;
    public static final SoundEffect ENTITY_ZOMBIE_INFECT;
    public static final SoundEffect ENTITY_ZOMBIE_PIGMAN_AMBIENT;
    public static final SoundEffect ENTITY_ZOMBIE_PIGMAN_ANGRY;
    public static final SoundEffect ENTITY_ZOMBIE_PIGMAN_DEATH;
    public static final SoundEffect ENTITY_ZOMBIE_PIGMAN_HURT;
    public static final SoundEffect ENTITY_ZOMBIE_STEP;
    public static final SoundEffect ENTITY_ZOMBIE_VILLAGER_AMBIENT;
    public static final SoundEffect ENTITY_ZOMBIE_VILLAGER_CONVERTED;
    public static final SoundEffect ENTITY_ZOMBIE_VILLAGER_CURE;
    public static final SoundEffect ENTITY_ZOMBIE_VILLAGER_DEATH;
    public static final SoundEffect ENTITY_ZOMBIE_VILLAGER_HURT;
    public static final SoundEffect ENTITY_ZOMBIE_VILLAGER_STEP;

    private static SoundEffect a(String s) {
        SoundEffect soundeffect = (SoundEffect) IRegistry.SOUND_EVENT.get(new MinecraftKey(s));

        if (soundeffect == null) {
            throw new IllegalStateException("Invalid Sound requested: " + s);
        } else {
            return soundeffect;
        }
    }

    static {
        if (!DispenserRegistry.a()) {
            throw new RuntimeException("Accessed Sounds before Bootstrap!");
        } else {
            AMBIENT_CAVE = a("ambient.cave");
            AMBIENT_UNDERWATER_ENTER = a("ambient.underwater.enter");
            AMBIENT_UNDERWATER_EXIT = a("ambient.underwater.exit");
            AMBIENT_UNDERWATER_LOOP = a("ambient.underwater.loop");
            AMBIENT_UNDERWATER_LOOP_ADDITIONS = a("ambient.underwater.loop.additions");
            AMBIENT_UNDERWATER_LOOP_ADDITIONS_RARE = a("ambient.underwater.loop.additions.rare");
            AMBIENT_UNDERWATER_LOOP_ADDITIONS_ULTRA_RARE = a("ambient.underwater.loop.additions.ultra_rare");
            BLOCK_ANVIL_BREAK = a("block.anvil.break");
            BLOCK_ANVIL_DESTROY = a("block.anvil.destroy");
            BLOCK_ANVIL_FALL = a("block.anvil.fall");
            BLOCK_ANVIL_HIT = a("block.anvil.hit");
            BLOCK_ANVIL_LAND = a("block.anvil.land");
            BLOCK_ANVIL_PLACE = a("block.anvil.place");
            BLOCK_ANVIL_STEP = a("block.anvil.step");
            BLOCK_ANVIL_USE = a("block.anvil.use");
            ITEM_ARMOR_EQUIP_CHAIN = a("item.armor.equip_chain");
            ITEM_ARMOR_EQUIP_DIAMOND = a("item.armor.equip_diamond");
            ITEM_ARMOR_EQUIP_ELYTRA = a("item.armor.equip_elytra");
            ITEM_ARMOR_EQUIP_GENERIC = a("item.armor.equip_generic");
            ITEM_ARMOR_EQUIP_GOLD = a("item.armor.equip_gold");
            ITEM_ARMOR_EQUIP_IRON = a("item.armor.equip_iron");
            ITEM_ARMOR_EQUIP_LEATHER = a("item.armor.equip_leather");
            ITEM_ARMOR_EQUIP_TURTLE = a("item.armor.equip_turtle");
            ENTITY_ARMOR_STAND_BREAK = a("entity.armor_stand.break");
            ENTITY_ARMOR_STAND_FALL = a("entity.armor_stand.fall");
            ENTITY_ARMOR_STAND_HIT = a("entity.armor_stand.hit");
            ENTITY_ARMOR_STAND_PLACE = a("entity.armor_stand.place");
            ENTITY_ARROW_HIT = a("entity.arrow.hit");
            ENTITY_ARROW_HIT_PLAYER = a("entity.arrow.hit_player");
            ENTITY_ARROW_SHOOT = a("entity.arrow.shoot");
            ITEM_AXE_STRIP = a("item.axe.strip");
            ENTITY_BAT_AMBIENT = a("entity.bat.ambient");
            ENTITY_BAT_DEATH = a("entity.bat.death");
            ENTITY_BAT_HURT = a("entity.bat.hurt");
            ENTITY_BAT_LOOP = a("entity.bat.loop");
            ENTITY_BAT_TAKEOFF = a("entity.bat.takeoff");
            BLOCK_BEACON_ACTIVATE = a("block.beacon.activate");
            BLOCK_BEACON_AMBIENT = a("block.beacon.ambient");
            BLOCK_BEACON_DEACTIVATE = a("block.beacon.deactivate");
            BLOCK_BEACON_POWER_SELECT = a("block.beacon.power_select");
            ENTITY_BLAZE_AMBIENT = a("entity.blaze.ambient");
            ENTITY_BLAZE_BURN = a("entity.blaze.burn");
            ENTITY_BLAZE_DEATH = a("entity.blaze.death");
            ENTITY_BLAZE_HURT = a("entity.blaze.hurt");
            ENTITY_BLAZE_SHOOT = a("entity.blaze.shoot");
            ENTITY_BOAT_PADDLE_LAND = a("entity.boat.paddle_land");
            ENTITY_BOAT_PADDLE_WATER = a("entity.boat.paddle_water");
            ENTITY_FISHING_BOBBER_RETRIEVE = a("entity.fishing_bobber.retrieve");
            ENTITY_FISHING_BOBBER_SPLASH = a("entity.fishing_bobber.splash");
            ENTITY_FISHING_BOBBER_THROW = a("entity.fishing_bobber.throw");
            ITEM_BOTTLE_EMPTY = a("item.bottle.empty");
            ITEM_BOTTLE_FILL = a("item.bottle.fill");
            ITEM_BOTTLE_FILL_DRAGONBREATH = a("item.bottle.fill_dragonbreath");
            BLOCK_BREWING_STAND_BREW = a("block.brewing_stand.brew");
            BLOCK_BUBBLE_COLUMN_BUBBLE_POP = a("block.bubble_column.bubble_pop");
            BLOCK_BUBBLE_COLUMN_UPWARDS_AMBIENT = a("block.bubble_column.upwards_ambient");
            BLOCK_BUBBLE_COLUMN_UPWARDS_INSIDE = a("block.bubble_column.upwards_inside");
            BLOCK_BUBBLE_COLUMN_WHIRLPOOL_AMBIENT = a("block.bubble_column.whirlpool_ambient");
            BLOCK_BUBBLE_COLUMN_WHIRLPOOL_INSIDE = a("block.bubble_column.whirlpool_inside");
            ITEM_BUCKET_EMPTY = a("item.bucket.empty");
            ITEM_BUCKET_EMPTY_FISH = a("item.bucket.empty_fish");
            ITEM_BUCKET_EMPTY_LAVA = a("item.bucket.empty_lava");
            ITEM_BUCKET_FILL = a("item.bucket.fill");
            ITEM_BUCKET_FILL_FISH = a("item.bucket.fill_fish");
            ITEM_BUCKET_FILL_LAVA = a("item.bucket.fill_lava");
            ENTITY_CAT_AMBIENT = a("entity.cat.ambient");
            ENTITY_CAT_DEATH = a("entity.cat.death");
            ENTITY_CAT_HISS = a("entity.cat.hiss");
            ENTITY_CAT_HURT = a("entity.cat.hurt");
            ENTITY_CAT_PURR = a("entity.cat.purr");
            ENTITY_CAT_PURREOW = a("entity.cat.purreow");
            BLOCK_CHEST_CLOSE = a("block.chest.close");
            BLOCK_CHEST_LOCKED = a("block.chest.locked");
            BLOCK_CHEST_OPEN = a("block.chest.open");
            ENTITY_CHICKEN_AMBIENT = a("entity.chicken.ambient");
            ENTITY_CHICKEN_DEATH = a("entity.chicken.death");
            ENTITY_CHICKEN_EGG = a("entity.chicken.egg");
            ENTITY_CHICKEN_HURT = a("entity.chicken.hurt");
            ENTITY_CHICKEN_STEP = a("entity.chicken.step");
            BLOCK_CHORUS_FLOWER_DEATH = a("block.chorus_flower.death");
            BLOCK_CHORUS_FLOWER_GROW = a("block.chorus_flower.grow");
            ITEM_CHORUS_FRUIT_TELEPORT = a("item.chorus_fruit.teleport");
            BLOCK_WOOL_BREAK = a("block.wool.break");
            BLOCK_WOOL_FALL = a("block.wool.fall");
            BLOCK_WOOL_HIT = a("block.wool.hit");
            BLOCK_WOOL_PLACE = a("block.wool.place");
            BLOCK_WOOL_STEP = a("block.wool.step");
            ENTITY_COD_AMBIENT = a("entity.cod.ambient");
            ENTITY_COD_DEATH = a("entity.cod.death");
            ENTITY_COD_FLOP = a("entity.cod.flop");
            ENTITY_COD_HURT = a("entity.cod.hurt");
            BLOCK_COMPARATOR_CLICK = a("block.comparator.click");
            BLOCK_CONDUIT_ACTIVATE = a("block.conduit.activate");
            BLOCK_CONDUIT_AMBIENT = a("block.conduit.ambient");
            BLOCK_CONDUIT_AMBIENT_SHORT = a("block.conduit.ambient.short");
            BLOCK_CONDUIT_ATTACK_TARGET = a("block.conduit.attack.target");
            BLOCK_CONDUIT_DEACTIVATE = a("block.conduit.deactivate");
            ENTITY_COW_AMBIENT = a("entity.cow.ambient");
            ENTITY_COW_DEATH = a("entity.cow.death");
            ENTITY_COW_HURT = a("entity.cow.hurt");
            ENTITY_COW_MILK = a("entity.cow.milk");
            ENTITY_COW_STEP = a("entity.cow.step");
            ENTITY_CREEPER_DEATH = a("entity.creeper.death");
            ENTITY_CREEPER_HURT = a("entity.creeper.hurt");
            ENTITY_CREEPER_PRIMED = a("entity.creeper.primed");
            BLOCK_DISPENSER_DISPENSE = a("block.dispenser.dispense");
            BLOCK_DISPENSER_FAIL = a("block.dispenser.fail");
            BLOCK_DISPENSER_LAUNCH = a("block.dispenser.launch");
            ENTITY_DOLPHIN_AMBIENT = a("entity.dolphin.ambient");
            ENTITY_DOLPHIN_AMBIENT_WATER = a("entity.dolphin.ambient_water");
            ENTITY_DOLPHIN_ATTACK = a("entity.dolphin.attack");
            ENTITY_DOLPHIN_DEATH = a("entity.dolphin.death");
            ENTITY_DOLPHIN_EAT = a("entity.dolphin.eat");
            ENTITY_DOLPHIN_HURT = a("entity.dolphin.hurt");
            ENTITY_DOLPHIN_JUMP = a("entity.dolphin.jump");
            ENTITY_DOLPHIN_PLAY = a("entity.dolphin.play");
            ENTITY_DOLPHIN_SPLASH = a("entity.dolphin.splash");
            ENTITY_DOLPHIN_SWIM = a("entity.dolphin.swim");
            ENTITY_DONKEY_AMBIENT = a("entity.donkey.ambient");
            ENTITY_DONKEY_ANGRY = a("entity.donkey.angry");
            ENTITY_DONKEY_CHEST = a("entity.donkey.chest");
            ENTITY_DONKEY_DEATH = a("entity.donkey.death");
            ENTITY_DONKEY_HURT = a("entity.donkey.hurt");
            ENTITY_DROWNED_AMBIENT = a("entity.drowned.ambient");
            ENTITY_DROWNED_AMBIENT_WATER = a("entity.drowned.ambient_water");
            ENTITY_DROWNED_DEATH = a("entity.drowned.death");
            ENTITY_DROWNED_DEATH_WATER = a("entity.drowned.death_water");
            ENTITY_DROWNED_HURT = a("entity.drowned.hurt");
            ENTITY_DROWNED_HURT_WATER = a("entity.drowned.hurt_water");
            ENTITY_DROWNED_SHOOT = a("entity.drowned.shoot");
            ENTITY_DROWNED_STEP = a("entity.drowned.step");
            ENTITY_DROWNED_SWIM = a("entity.drowned.swim");
            ENTITY_EGG_THROW = a("entity.egg.throw");
            ENTITY_ELDER_GUARDIAN_AMBIENT = a("entity.elder_guardian.ambient");
            ENTITY_ELDER_GUARDIAN_AMBIENT_LAND = a("entity.elder_guardian.ambient_land");
            ENTITY_ELDER_GUARDIAN_CURSE = a("entity.elder_guardian.curse");
            ENTITY_ELDER_GUARDIAN_DEATH = a("entity.elder_guardian.death");
            ENTITY_ELDER_GUARDIAN_DEATH_LAND = a("entity.elder_guardian.death_land");
            ENTITY_ELDER_GUARDIAN_FLOP = a("entity.elder_guardian.flop");
            ENTITY_ELDER_GUARDIAN_HURT = a("entity.elder_guardian.hurt");
            ENTITY_ELDER_GUARDIAN_HURT_LAND = a("entity.elder_guardian.hurt_land");
            ITEM_ELYTRA_FLYING = a("item.elytra.flying");
            BLOCK_ENCHANTMENT_TABLE_USE = a("block.enchantment_table.use");
            BLOCK_ENDER_CHEST_CLOSE = a("block.ender_chest.close");
            BLOCK_ENDER_CHEST_OPEN = a("block.ender_chest.open");
            ENTITY_ENDER_DRAGON_AMBIENT = a("entity.ender_dragon.ambient");
            ENTITY_ENDER_DRAGON_DEATH = a("entity.ender_dragon.death");
            ENTITY_DRAGON_FIREBALL_EXPLODE = a("entity.dragon_fireball.explode");
            ENTITY_ENDER_DRAGON_FLAP = a("entity.ender_dragon.flap");
            ENTITY_ENDER_DRAGON_GROWL = a("entity.ender_dragon.growl");
            ENTITY_ENDER_DRAGON_HURT = a("entity.ender_dragon.hurt");
            ENTITY_ENDER_DRAGON_SHOOT = a("entity.ender_dragon.shoot");
            ENTITY_ENDER_EYE_DEATH = a("entity.ender_eye.death");
            ENTITY_ENDER_EYE_LAUNCH = a("entity.ender_eye.launch");
            ENTITY_ENDERMAN_AMBIENT = a("entity.enderman.ambient");
            ENTITY_ENDERMAN_DEATH = a("entity.enderman.death");
            ENTITY_ENDERMAN_HURT = a("entity.enderman.hurt");
            ENTITY_ENDERMAN_SCREAM = a("entity.enderman.scream");
            ENTITY_ENDERMAN_STARE = a("entity.enderman.stare");
            ENTITY_ENDERMAN_TELEPORT = a("entity.enderman.teleport");
            ENTITY_ENDERMITE_AMBIENT = a("entity.endermite.ambient");
            ENTITY_ENDERMITE_DEATH = a("entity.endermite.death");
            ENTITY_ENDERMITE_HURT = a("entity.endermite.hurt");
            ENTITY_ENDERMITE_STEP = a("entity.endermite.step");
            ENTITY_ENDER_PEARL_THROW = a("entity.ender_pearl.throw");
            BLOCK_END_GATEWAY_SPAWN = a("block.end_gateway.spawn");
            BLOCK_END_PORTAL_FRAME_FILL = a("block.end_portal_frame.fill");
            BLOCK_END_PORTAL_SPAWN = a("block.end_portal.spawn");
            ENTITY_EVOKER_AMBIENT = a("entity.evoker.ambient");
            ENTITY_EVOKER_CAST_SPELL = a("entity.evoker.cast_spell");
            ENTITY_EVOKER_DEATH = a("entity.evoker.death");
            ENTITY_EVOKER_FANGS_ATTACK = a("entity.evoker_fangs.attack");
            ENTITY_EVOKER_HURT = a("entity.evoker.hurt");
            ENTITY_EVOKER_PREPARE_ATTACK = a("entity.evoker.prepare_attack");
            ENTITY_EVOKER_PREPARE_SUMMON = a("entity.evoker.prepare_summon");
            ENTITY_EVOKER_PREPARE_WOLOLO = a("entity.evoker.prepare_wololo");
            ENTITY_EXPERIENCE_BOTTLE_THROW = a("entity.experience_bottle.throw");
            ENTITY_EXPERIENCE_ORB_PICKUP = a("entity.experience_orb.pickup");
            BLOCK_FENCE_GATE_CLOSE = a("block.fence_gate.close");
            BLOCK_FENCE_GATE_OPEN = a("block.fence_gate.open");
            ITEM_FIRECHARGE_USE = a("item.firecharge.use");
            ENTITY_FIREWORK_ROCKET_BLAST = a("entity.firework_rocket.blast");
            ENTITY_FIREWORK_ROCKET_BLAST_FAR = a("entity.firework_rocket.blast_far");
            ENTITY_FIREWORK_ROCKET_LARGE_BLAST = a("entity.firework_rocket.large_blast");
            ENTITY_FIREWORK_ROCKET_LARGE_BLAST_FAR = a("entity.firework_rocket.large_blast_far");
            ENTITY_FIREWORK_ROCKET_LAUNCH = a("entity.firework_rocket.launch");
            ENTITY_FIREWORK_ROCKET_SHOOT = a("entity.firework_rocket.shoot");
            ENTITY_FIREWORK_ROCKET_TWINKLE = a("entity.firework_rocket.twinkle");
            ENTITY_FIREWORK_ROCKET_TWINKLE_FAR = a("entity.firework_rocket.twinkle_far");
            BLOCK_FIRE_AMBIENT = a("block.fire.ambient");
            BLOCK_FIRE_EXTINGUISH = a("block.fire.extinguish");
            ENTITY_FISH_SWIM = a("entity.fish.swim");
            ITEM_FLINTANDSTEEL_USE = a("item.flintandsteel.use");
            BLOCK_FURNACE_FIRE_CRACKLE = a("block.furnace.fire_crackle");
            ENTITY_GENERIC_BIG_FALL = a("entity.generic.big_fall");
            ENTITY_GENERIC_BURN = a("entity.generic.burn");
            ENTITY_GENERIC_DEATH = a("entity.generic.death");
            ENTITY_GENERIC_DRINK = a("entity.generic.drink");
            ENTITY_GENERIC_EAT = a("entity.generic.eat");
            ENTITY_GENERIC_EXPLODE = a("entity.generic.explode");
            ENTITY_GENERIC_EXTINGUISH_FIRE = a("entity.generic.extinguish_fire");
            ENTITY_GENERIC_HURT = a("entity.generic.hurt");
            ENTITY_GENERIC_SMALL_FALL = a("entity.generic.small_fall");
            ENTITY_GENERIC_SPLASH = a("entity.generic.splash");
            ENTITY_GENERIC_SWIM = a("entity.generic.swim");
            ENTITY_GHAST_AMBIENT = a("entity.ghast.ambient");
            ENTITY_GHAST_DEATH = a("entity.ghast.death");
            ENTITY_GHAST_HURT = a("entity.ghast.hurt");
            ENTITY_GHAST_SCREAM = a("entity.ghast.scream");
            ENTITY_GHAST_SHOOT = a("entity.ghast.shoot");
            ENTITY_GHAST_WARN = a("entity.ghast.warn");
            BLOCK_GLASS_BREAK = a("block.glass.break");
            BLOCK_GLASS_FALL = a("block.glass.fall");
            BLOCK_GLASS_HIT = a("block.glass.hit");
            BLOCK_GLASS_PLACE = a("block.glass.place");
            BLOCK_GLASS_STEP = a("block.glass.step");
            BLOCK_GRASS_BREAK = a("block.grass.break");
            BLOCK_GRASS_FALL = a("block.grass.fall");
            BLOCK_GRASS_HIT = a("block.grass.hit");
            BLOCK_GRASS_PLACE = a("block.grass.place");
            BLOCK_GRASS_STEP = a("block.grass.step");
            BLOCK_WET_GRASS_BREAK = a("block.wet_grass.break");
            BLOCK_WET_GRASS_FALL = a("block.wet_grass.fall");
            BLOCK_WET_GRASS_HIT = a("block.wet_grass.hit");
            BLOCK_WET_GRASS_PLACE = a("block.wet_grass.place");
            BLOCK_WET_GRASS_STEP = a("block.wet_grass.step");
            BLOCK_CORAL_BLOCK_BREAK = a("block.coral_block.break");
            BLOCK_CORAL_BLOCK_FALL = a("block.coral_block.fall");
            BLOCK_CORAL_BLOCK_HIT = a("block.coral_block.hit");
            BLOCK_CORAL_BLOCK_PLACE = a("block.coral_block.place");
            BLOCK_CORAL_BLOCK_STEP = a("block.coral_block.step");
            BLOCK_GRAVEL_BREAK = a("block.gravel.break");
            BLOCK_GRAVEL_FALL = a("block.gravel.fall");
            BLOCK_GRAVEL_HIT = a("block.gravel.hit");
            BLOCK_GRAVEL_PLACE = a("block.gravel.place");
            BLOCK_GRAVEL_STEP = a("block.gravel.step");
            ENTITY_GUARDIAN_AMBIENT = a("entity.guardian.ambient");
            ENTITY_GUARDIAN_AMBIENT_LAND = a("entity.guardian.ambient_land");
            ENTITY_GUARDIAN_ATTACK = a("entity.guardian.attack");
            ENTITY_GUARDIAN_DEATH = a("entity.guardian.death");
            ENTITY_GUARDIAN_DEATH_LAND = a("entity.guardian.death_land");
            ENTITY_GUARDIAN_FLOP = a("entity.guardian.flop");
            ENTITY_GUARDIAN_HURT = a("entity.guardian.hurt");
            ENTITY_GUARDIAN_HURT_LAND = a("entity.guardian.hurt_land");
            ITEM_HOE_TILL = a("item.hoe.till");
            ENTITY_HORSE_AMBIENT = a("entity.horse.ambient");
            ENTITY_HORSE_ANGRY = a("entity.horse.angry");
            ENTITY_HORSE_ARMOR = a("entity.horse.armor");
            ENTITY_HORSE_BREATHE = a("entity.horse.breathe");
            ENTITY_HORSE_DEATH = a("entity.horse.death");
            ENTITY_HORSE_EAT = a("entity.horse.eat");
            ENTITY_HORSE_GALLOP = a("entity.horse.gallop");
            ENTITY_HORSE_HURT = a("entity.horse.hurt");
            ENTITY_HORSE_JUMP = a("entity.horse.jump");
            ENTITY_HORSE_LAND = a("entity.horse.land");
            ENTITY_HORSE_SADDLE = a("entity.horse.saddle");
            ENTITY_HORSE_STEP = a("entity.horse.step");
            ENTITY_HORSE_STEP_WOOD = a("entity.horse.step_wood");
            ENTITY_HOSTILE_BIG_FALL = a("entity.hostile.big_fall");
            ENTITY_HOSTILE_DEATH = a("entity.hostile.death");
            ENTITY_HOSTILE_HURT = a("entity.hostile.hurt");
            ENTITY_HOSTILE_SMALL_FALL = a("entity.hostile.small_fall");
            ENTITY_HOSTILE_SPLASH = a("entity.hostile.splash");
            ENTITY_HOSTILE_SWIM = a("entity.hostile.swim");
            ENTITY_HUSK_AMBIENT = a("entity.husk.ambient");
            ENTITY_HUSK_CONVERTED_TO_ZOMBIE = a("entity.husk.converted_to_zombie");
            ENTITY_HUSK_DEATH = a("entity.husk.death");
            ENTITY_HUSK_HURT = a("entity.husk.hurt");
            ENTITY_HUSK_STEP = a("entity.husk.step");
            ENTITY_ILLUSIONER_AMBIENT = a("entity.illusioner.ambient");
            ENTITY_ILLUSIONER_CAST_SPELL = a("entity.illusioner.cast_spell");
            ENTITY_ILLUSIONER_DEATH = a("entity.illusioner.death");
            ENTITY_ILLUSIONER_HURT = a("entity.illusioner.hurt");
            ENTITY_ILLUSIONER_MIRROR_MOVE = a("entity.illusioner.mirror_move");
            ENTITY_ILLUSIONER_PREPARE_BLINDNESS = a("entity.illusioner.prepare_blindness");
            ENTITY_ILLUSIONER_PREPARE_MIRROR = a("entity.illusioner.prepare_mirror");
            BLOCK_IRON_DOOR_CLOSE = a("block.iron_door.close");
            BLOCK_IRON_DOOR_OPEN = a("block.iron_door.open");
            ENTITY_IRON_GOLEM_ATTACK = a("entity.iron_golem.attack");
            ENTITY_IRON_GOLEM_DEATH = a("entity.iron_golem.death");
            ENTITY_IRON_GOLEM_HURT = a("entity.iron_golem.hurt");
            ENTITY_IRON_GOLEM_STEP = a("entity.iron_golem.step");
            BLOCK_IRON_TRAPDOOR_CLOSE = a("block.iron_trapdoor.close");
            BLOCK_IRON_TRAPDOOR_OPEN = a("block.iron_trapdoor.open");
            ENTITY_ITEM_FRAME_ADD_ITEM = a("entity.item_frame.add_item");
            ENTITY_ITEM_FRAME_BREAK = a("entity.item_frame.break");
            ENTITY_ITEM_FRAME_PLACE = a("entity.item_frame.place");
            ENTITY_ITEM_FRAME_REMOVE_ITEM = a("entity.item_frame.remove_item");
            ENTITY_ITEM_FRAME_ROTATE_ITEM = a("entity.item_frame.rotate_item");
            ENTITY_ITEM_BREAK = a("entity.item.break");
            ENTITY_ITEM_PICKUP = a("entity.item.pickup");
            BLOCK_LADDER_BREAK = a("block.ladder.break");
            BLOCK_LADDER_FALL = a("block.ladder.fall");
            BLOCK_LADDER_HIT = a("block.ladder.hit");
            BLOCK_LADDER_PLACE = a("block.ladder.place");
            BLOCK_LADDER_STEP = a("block.ladder.step");
            BLOCK_LAVA_AMBIENT = a("block.lava.ambient");
            BLOCK_LAVA_EXTINGUISH = a("block.lava.extinguish");
            BLOCK_LAVA_POP = a("block.lava.pop");
            ENTITY_LEASH_KNOT_BREAK = a("entity.leash_knot.break");
            ENTITY_LEASH_KNOT_PLACE = a("entity.leash_knot.place");
            BLOCK_LEVER_CLICK = a("block.lever.click");
            ENTITY_LIGHTNING_BOLT_IMPACT = a("entity.lightning_bolt.impact");
            ENTITY_LIGHTNING_BOLT_THUNDER = a("entity.lightning_bolt.thunder");
            ENTITY_LINGERING_POTION_THROW = a("entity.lingering_potion.throw");
            ENTITY_LLAMA_AMBIENT = a("entity.llama.ambient");
            ENTITY_LLAMA_ANGRY = a("entity.llama.angry");
            ENTITY_LLAMA_CHEST = a("entity.llama.chest");
            ENTITY_LLAMA_DEATH = a("entity.llama.death");
            ENTITY_LLAMA_EAT = a("entity.llama.eat");
            ENTITY_LLAMA_HURT = a("entity.llama.hurt");
            ENTITY_LLAMA_SPIT = a("entity.llama.spit");
            ENTITY_LLAMA_STEP = a("entity.llama.step");
            ENTITY_LLAMA_SWAG = a("entity.llama.swag");
            ENTITY_MAGMA_CUBE_DEATH = a("entity.magma_cube.death");
            ENTITY_MAGMA_CUBE_HURT = a("entity.magma_cube.hurt");
            ENTITY_MAGMA_CUBE_JUMP = a("entity.magma_cube.jump");
            ENTITY_MAGMA_CUBE_SQUISH = a("entity.magma_cube.squish");
            BLOCK_METAL_BREAK = a("block.metal.break");
            BLOCK_METAL_FALL = a("block.metal.fall");
            BLOCK_METAL_HIT = a("block.metal.hit");
            BLOCK_METAL_PLACE = a("block.metal.place");
            BLOCK_METAL_PRESSURE_PLATE_CLICK_OFF = a("block.metal_pressure_plate.click_off");
            BLOCK_METAL_PRESSURE_PLATE_CLICK_ON = a("block.metal_pressure_plate.click_on");
            BLOCK_METAL_STEP = a("block.metal.step");
            ENTITY_MINECART_INSIDE = a("entity.minecart.inside");
            ENTITY_MINECART_RIDING = a("entity.minecart.riding");
            ENTITY_MOOSHROOM_SHEAR = a("entity.mooshroom.shear");
            ENTITY_MULE_AMBIENT = a("entity.mule.ambient");
            ENTITY_MULE_CHEST = a("entity.mule.chest");
            ENTITY_MULE_DEATH = a("entity.mule.death");
            ENTITY_MULE_HURT = a("entity.mule.hurt");
            MUSIC_CREATIVE = a("music.creative");
            MUSIC_CREDITS = a("music.credits");
            MUSIC_DRAGON = a("music.dragon");
            MUSIC_END = a("music.end");
            MUSIC_GAME = a("music.game");
            MUSIC_MENU = a("music.menu");
            MUSIC_NETHER = a("music.nether");
            MUSIC_UNDER_WATER = a("music.under_water");
            BLOCK_NOTE_BLOCK_BASEDRUM = a("block.note_block.basedrum");
            BLOCK_NOTE_BLOCK_BASS = a("block.note_block.bass");
            BLOCK_NOTE_BLOCK_BELL = a("block.note_block.bell");
            BLOCK_NOTE_BLOCK_CHIME = a("block.note_block.chime");
            BLOCK_NOTE_BLOCK_FLUTE = a("block.note_block.flute");
            BLOCK_NOTE_BLOCK_GUITAR = a("block.note_block.guitar");
            BLOCK_NOTE_BLOCK_HARP = a("block.note_block.harp");
            BLOCK_NOTE_BLOCK_HAT = a("block.note_block.hat");
            BLOCK_NOTE_BLOCK_PLING = a("block.note_block.pling");
            BLOCK_NOTE_BLOCK_SNARE = a("block.note_block.snare");
            BLOCK_NOTE_BLOCK_XYLOPHONE = a("block.note_block.xylophone");
            ENTITY_PAINTING_BREAK = a("entity.painting.break");
            ENTITY_PAINTING_PLACE = a("entity.painting.place");
            ENTITY_PARROT_AMBIENT = a("entity.parrot.ambient");
            ENTITY_PARROT_DEATH = a("entity.parrot.death");
            ENTITY_PARROT_EAT = a("entity.parrot.eat");
            ENTITY_PARROT_FLY = a("entity.parrot.fly");
            ENTITY_PARROT_HURT = a("entity.parrot.hurt");
            ENTITY_PARROT_IMITATE_BLAZE = a("entity.parrot.imitate.blaze");
            ENTITY_PARROT_IMITATE_CREEPER = a("entity.parrot.imitate.creeper");
            ENTITY_PARROT_IMITATE_DROWNED = a("entity.parrot.imitate.drowned");
            ENTITY_PARROT_IMITATE_ELDER_GUARDIAN = a("entity.parrot.imitate.elder_guardian");
            ENTITY_PARROT_IMITATE_ENDER_DRAGON = a("entity.parrot.imitate.ender_dragon");
            ENTITY_PARROT_IMITATE_ENDERMAN = a("entity.parrot.imitate.enderman");
            ENTITY_PARROT_IMITATE_ENDERMITE = a("entity.parrot.imitate.endermite");
            ENTITY_PARROT_IMITATE_EVOKER = a("entity.parrot.imitate.evoker");
            ENTITY_PARROT_IMITATE_GHAST = a("entity.parrot.imitate.ghast");
            ENTITY_PARROT_IMITATE_HUSK = a("entity.parrot.imitate.husk");
            ENTITY_PARROT_IMITATE_ILLUSIONER = a("entity.parrot.imitate.illusioner");
            ENTITY_PARROT_IMITATE_MAGMA_CUBE = a("entity.parrot.imitate.magma_cube");
            ENTITY_PARROT_IMITATE_PHANTOM = a("entity.parrot.imitate.phantom");
            ENTITY_PARROT_IMITATE_POLAR_BEAR = a("entity.parrot.imitate.polar_bear");
            ENTITY_PARROT_IMITATE_SHULKER = a("entity.parrot.imitate.shulker");
            ENTITY_PARROT_IMITATE_SILVERFISH = a("entity.parrot.imitate.silverfish");
            ENTITY_PARROT_IMITATE_SKELETON = a("entity.parrot.imitate.skeleton");
            ENTITY_PARROT_IMITATE_SLIME = a("entity.parrot.imitate.slime");
            ENTITY_PARROT_IMITATE_SPIDER = a("entity.parrot.imitate.spider");
            ENTITY_PARROT_IMITATE_STRAY = a("entity.parrot.imitate.stray");
            ENTITY_PARROT_IMITATE_VEX = a("entity.parrot.imitate.vex");
            ENTITY_PARROT_IMITATE_VINDICATOR = a("entity.parrot.imitate.vindicator");
            ENTITY_PARROT_IMITATE_WITCH = a("entity.parrot.imitate.witch");
            ENTITY_PARROT_IMITATE_WITHER = a("entity.parrot.imitate.wither");
            ENTITY_PARROT_IMITATE_WITHER_SKELETON = a("entity.parrot.imitate.wither_skeleton");
            ENTITY_PARROT_IMITATE_WOLF = a("entity.parrot.imitate.wolf");
            ENTITY_PARROT_IMITATE_ZOMBIE = a("entity.parrot.imitate.zombie");
            ENTITY_PARROT_IMITATE_ZOMBIE_PIGMAN = a("entity.parrot.imitate.zombie_pigman");
            ENTITY_PARROT_IMITATE_ZOMBIE_VILLAGER = a("entity.parrot.imitate.zombie_villager");
            ENTITY_PARROT_STEP = a("entity.parrot.step");
            ENTITY_PHANTOM_AMBIENT = a("entity.phantom.ambient");
            ENTITY_PHANTOM_BITE = a("entity.phantom.bite");
            ENTITY_PHANTOM_DEATH = a("entity.phantom.death");
            ENTITY_PHANTOM_FLAP = a("entity.phantom.flap");
            ENTITY_PHANTOM_HURT = a("entity.phantom.hurt");
            ENTITY_PHANTOM_SWOOP = a("entity.phantom.swoop");
            ENTITY_PIG_AMBIENT = a("entity.pig.ambient");
            ENTITY_PIG_DEATH = a("entity.pig.death");
            ENTITY_PIG_HURT = a("entity.pig.hurt");
            ENTITY_PIG_SADDLE = a("entity.pig.saddle");
            ENTITY_PIG_STEP = a("entity.pig.step");
            BLOCK_PISTON_CONTRACT = a("block.piston.contract");
            BLOCK_PISTON_EXTEND = a("block.piston.extend");
            ENTITY_PLAYER_ATTACK_CRIT = a("entity.player.attack.crit");
            ENTITY_PLAYER_ATTACK_KNOCKBACK = a("entity.player.attack.knockback");
            ENTITY_PLAYER_ATTACK_NODAMAGE = a("entity.player.attack.nodamage");
            ENTITY_PLAYER_ATTACK_STRONG = a("entity.player.attack.strong");
            ENTITY_PLAYER_ATTACK_SWEEP = a("entity.player.attack.sweep");
            ENTITY_PLAYER_ATTACK_WEAK = a("entity.player.attack.weak");
            ENTITY_PLAYER_BIG_FALL = a("entity.player.big_fall");
            ENTITY_PLAYER_BREATH = a("entity.player.breath");
            ENTITY_PLAYER_BURP = a("entity.player.burp");
            ENTITY_PLAYER_DEATH = a("entity.player.death");
            ENTITY_PLAYER_HURT = a("entity.player.hurt");
            ENTITY_PLAYER_HURT_DROWN = a("entity.player.hurt_drown");
            ENTITY_PLAYER_HURT_ON_FIRE = a("entity.player.hurt_on_fire");
            ENTITY_PLAYER_LEVELUP = a("entity.player.levelup");
            ENTITY_PLAYER_SMALL_FALL = a("entity.player.small_fall");
            ENTITY_PLAYER_SPLASH = a("entity.player.splash");
            ENTITY_PLAYER_SPLASH_HIGH_SPEED = a("entity.player.splash.high_speed");
            ENTITY_PLAYER_SWIM = a("entity.player.swim");
            ENTITY_POLAR_BEAR_AMBIENT = a("entity.polar_bear.ambient");
            ENTITY_POLAR_BEAR_AMBIENT_BABY = a("entity.polar_bear.ambient_baby");
            ENTITY_POLAR_BEAR_DEATH = a("entity.polar_bear.death");
            ENTITY_POLAR_BEAR_HURT = a("entity.polar_bear.hurt");
            ENTITY_POLAR_BEAR_STEP = a("entity.polar_bear.step");
            ENTITY_POLAR_BEAR_WARNING = a("entity.polar_bear.warning");
            BLOCK_PORTAL_AMBIENT = a("block.portal.ambient");
            BLOCK_PORTAL_TRAVEL = a("block.portal.travel");
            BLOCK_PORTAL_TRIGGER = a("block.portal.trigger");
            ENTITY_PUFFER_FISH_AMBIENT = a("entity.puffer_fish.ambient");
            ENTITY_PUFFER_FISH_BLOW_OUT = a("entity.puffer_fish.blow_out");
            ENTITY_PUFFER_FISH_BLOW_UP = a("entity.puffer_fish.blow_up");
            ENTITY_PUFFER_FISH_DEATH = a("entity.puffer_fish.death");
            ENTITY_PUFFER_FISH_FLOP = a("entity.puffer_fish.flop");
            ENTITY_PUFFER_FISH_HURT = a("entity.puffer_fish.hurt");
            ENTITY_PUFFER_FISH_STING = a("entity.puffer_fish.sting");
            BLOCK_PUMPKIN_CARVE = a("block.pumpkin.carve");
            ENTITY_RABBIT_AMBIENT = a("entity.rabbit.ambient");
            ENTITY_RABBIT_ATTACK = a("entity.rabbit.attack");
            ENTITY_RABBIT_DEATH = a("entity.rabbit.death");
            ENTITY_RABBIT_HURT = a("entity.rabbit.hurt");
            ENTITY_RABBIT_JUMP = a("entity.rabbit.jump");
            MUSIC_DISC_11 = a("music_disc.11");
            MUSIC_DISC_13 = a("music_disc.13");
            MUSIC_DISC_BLOCKS = a("music_disc.blocks");
            MUSIC_DISC_CAT = a("music_disc.cat");
            MUSIC_DISC_CHIRP = a("music_disc.chirp");
            MUSIC_DISC_FAR = a("music_disc.far");
            MUSIC_DISC_MALL = a("music_disc.mall");
            MUSIC_DISC_MELLOHI = a("music_disc.mellohi");
            MUSIC_DISC_STAL = a("music_disc.stal");
            MUSIC_DISC_STRAD = a("music_disc.strad");
            MUSIC_DISC_WAIT = a("music_disc.wait");
            MUSIC_DISC_WARD = a("music_disc.ward");
            BLOCK_REDSTONE_TORCH_BURNOUT = a("block.redstone_torch.burnout");
            ENTITY_SALMON_AMBIENT = a("entity.salmon.ambient");
            ENTITY_SALMON_DEATH = a("entity.salmon.death");
            ENTITY_SALMON_FLOP = a("entity.salmon.flop");
            ENTITY_SALMON_HURT = a("entity.salmon.hurt");
            BLOCK_SAND_BREAK = a("block.sand.break");
            BLOCK_SAND_FALL = a("block.sand.fall");
            BLOCK_SAND_HIT = a("block.sand.hit");
            BLOCK_SAND_PLACE = a("block.sand.place");
            BLOCK_SAND_STEP = a("block.sand.step");
            ENTITY_SHEEP_AMBIENT = a("entity.sheep.ambient");
            ENTITY_SHEEP_DEATH = a("entity.sheep.death");
            ENTITY_SHEEP_HURT = a("entity.sheep.hurt");
            ENTITY_SHEEP_SHEAR = a("entity.sheep.shear");
            ENTITY_SHEEP_STEP = a("entity.sheep.step");
            ITEM_SHIELD_BLOCK = a("item.shield.block");
            ITEM_SHIELD_BREAK = a("item.shield.break");
            ITEM_SHOVEL_FLATTEN = a("item.shovel.flatten");
            ENTITY_SHULKER_AMBIENT = a("entity.shulker.ambient");
            BLOCK_SHULKER_BOX_CLOSE = a("block.shulker_box.close");
            BLOCK_SHULKER_BOX_OPEN = a("block.shulker_box.open");
            ENTITY_SHULKER_BULLET_HIT = a("entity.shulker_bullet.hit");
            ENTITY_SHULKER_BULLET_HURT = a("entity.shulker_bullet.hurt");
            ENTITY_SHULKER_CLOSE = a("entity.shulker.close");
            ENTITY_SHULKER_DEATH = a("entity.shulker.death");
            ENTITY_SHULKER_HURT = a("entity.shulker.hurt");
            ENTITY_SHULKER_HURT_CLOSED = a("entity.shulker.hurt_closed");
            ENTITY_SHULKER_OPEN = a("entity.shulker.open");
            ENTITY_SHULKER_SHOOT = a("entity.shulker.shoot");
            ENTITY_SHULKER_TELEPORT = a("entity.shulker.teleport");
            ENTITY_SILVERFISH_AMBIENT = a("entity.silverfish.ambient");
            ENTITY_SILVERFISH_DEATH = a("entity.silverfish.death");
            ENTITY_SILVERFISH_HURT = a("entity.silverfish.hurt");
            ENTITY_SILVERFISH_STEP = a("entity.silverfish.step");
            ENTITY_SKELETON_AMBIENT = a("entity.skeleton.ambient");
            ENTITY_SKELETON_DEATH = a("entity.skeleton.death");
            ENTITY_SKELETON_HORSE_AMBIENT = a("entity.skeleton_horse.ambient");
            ENTITY_SKELETON_HORSE_DEATH = a("entity.skeleton_horse.death");
            ENTITY_SKELETON_HORSE_HURT = a("entity.skeleton_horse.hurt");
            ENTITY_SKELETON_HORSE_SWIM = a("entity.skeleton_horse.swim");
            ENTITY_SKELETON_HORSE_AMBIENT_WATER = a("entity.skeleton_horse.ambient_water");
            ENTITY_SKELETON_HORSE_GALLOP_WATER = a("entity.skeleton_horse.gallop_water");
            ENTITY_SKELETON_HORSE_JUMP_WATER = a("entity.skeleton_horse.jump_water");
            ENTITY_SKELETON_HORSE_STEP_WATER = a("entity.skeleton_horse.step_water");
            ENTITY_SKELETON_HURT = a("entity.skeleton.hurt");
            ENTITY_SKELETON_SHOOT = a("entity.skeleton.shoot");
            ENTITY_SKELETON_STEP = a("entity.skeleton.step");
            ENTITY_SLIME_ATTACK = a("entity.slime.attack");
            ENTITY_SLIME_DEATH = a("entity.slime.death");
            ENTITY_SLIME_HURT = a("entity.slime.hurt");
            ENTITY_SLIME_JUMP = a("entity.slime.jump");
            ENTITY_SLIME_SQUISH = a("entity.slime.squish");
            BLOCK_SLIME_BLOCK_BREAK = a("block.slime_block.break");
            BLOCK_SLIME_BLOCK_FALL = a("block.slime_block.fall");
            BLOCK_SLIME_BLOCK_HIT = a("block.slime_block.hit");
            BLOCK_SLIME_BLOCK_PLACE = a("block.slime_block.place");
            BLOCK_SLIME_BLOCK_STEP = a("block.slime_block.step");
            ENTITY_MAGMA_CUBE_DEATH_SMALL = a("entity.magma_cube.death_small");
            ENTITY_MAGMA_CUBE_HURT_SMALL = a("entity.magma_cube.hurt_small");
            ENTITY_MAGMA_CUBE_SQUISH_SMALL = a("entity.magma_cube.squish_small");
            ENTITY_SLIME_DEATH_SMALL = a("entity.slime.death_small");
            ENTITY_SLIME_HURT_SMALL = a("entity.slime.hurt_small");
            ENTITY_SLIME_JUMP_SMALL = a("entity.slime.jump_small");
            ENTITY_SLIME_SQUISH_SMALL = a("entity.slime.squish_small");
            ENTITY_SNOWBALL_THROW = a("entity.snowball.throw");
            BLOCK_SNOW_BREAK = a("block.snow.break");
            BLOCK_SNOW_FALL = a("block.snow.fall");
            ENTITY_SNOW_GOLEM_AMBIENT = a("entity.snow_golem.ambient");
            ENTITY_SNOW_GOLEM_DEATH = a("entity.snow_golem.death");
            ENTITY_SNOW_GOLEM_HURT = a("entity.snow_golem.hurt");
            ENTITY_SNOW_GOLEM_SHOOT = a("entity.snow_golem.shoot");
            BLOCK_SNOW_HIT = a("block.snow.hit");
            BLOCK_SNOW_PLACE = a("block.snow.place");
            BLOCK_SNOW_STEP = a("block.snow.step");
            ENTITY_SPIDER_AMBIENT = a("entity.spider.ambient");
            ENTITY_SPIDER_DEATH = a("entity.spider.death");
            ENTITY_SPIDER_HURT = a("entity.spider.hurt");
            ENTITY_SPIDER_STEP = a("entity.spider.step");
            ENTITY_SPLASH_POTION_BREAK = a("entity.splash_potion.break");
            ENTITY_SPLASH_POTION_THROW = a("entity.splash_potion.throw");
            ENTITY_SQUID_AMBIENT = a("entity.squid.ambient");
            ENTITY_SQUID_DEATH = a("entity.squid.death");
            ENTITY_SQUID_HURT = a("entity.squid.hurt");
            ENTITY_SQUID_SQUIRT = a("entity.squid.squirt");
            BLOCK_STONE_BREAK = a("block.stone.break");
            BLOCK_STONE_BUTTON_CLICK_OFF = a("block.stone_button.click_off");
            BLOCK_STONE_BUTTON_CLICK_ON = a("block.stone_button.click_on");
            BLOCK_STONE_FALL = a("block.stone.fall");
            BLOCK_STONE_HIT = a("block.stone.hit");
            BLOCK_STONE_PLACE = a("block.stone.place");
            BLOCK_STONE_PRESSURE_PLATE_CLICK_OFF = a("block.stone_pressure_plate.click_off");
            BLOCK_STONE_PRESSURE_PLATE_CLICK_ON = a("block.stone_pressure_plate.click_on");
            BLOCK_STONE_STEP = a("block.stone.step");
            ENTITY_STRAY_AMBIENT = a("entity.stray.ambient");
            ENTITY_STRAY_DEATH = a("entity.stray.death");
            ENTITY_STRAY_HURT = a("entity.stray.hurt");
            ENTITY_STRAY_STEP = a("entity.stray.step");
            ENCHANT_THORNS_HIT = a("enchant.thorns.hit");
            ENTITY_TNT_PRIMED = a("entity.tnt.primed");
            ITEM_TOTEM_USE = a("item.totem.use");
            ITEM_TRIDENT_HIT = a("item.trident.hit");
            ITEM_TRIDENT_HIT_GROUND = a("item.trident.hit_ground");
            ITEM_TRIDENT_RETURN = a("item.trident.return");
            ITEM_TRIDENT_RIPTIDE_1 = a("item.trident.riptide_1");
            ITEM_TRIDENT_RIPTIDE_2 = a("item.trident.riptide_2");
            ITEM_TRIDENT_RIPTIDE_3 = a("item.trident.riptide_3");
            ITEM_TRIDENT_THROW = a("item.trident.throw");
            ITEM_TRIDENT_THUNDER = a("item.trident.thunder");
            BLOCK_TRIPWIRE_ATTACH = a("block.tripwire.attach");
            BLOCK_TRIPWIRE_CLICK_OFF = a("block.tripwire.click_off");
            BLOCK_TRIPWIRE_CLICK_ON = a("block.tripwire.click_on");
            BLOCK_TRIPWIRE_DETACH = a("block.tripwire.detach");
            ENTITY_TROPICAL_FISH_AMBIENT = a("entity.tropical_fish.ambient");
            ENTITY_TROPICAL_FISH_DEATH = a("entity.tropical_fish.death");
            ENTITY_TROPICAL_FISH_FLOP = a("entity.tropical_fish.flop");
            ENTITY_TROPICAL_FISH_HURT = a("entity.tropical_fish.hurt");
            ENTITY_TURTLE_AMBIENT_LAND = a("entity.turtle.ambient_land");
            ENTITY_TURTLE_DEATH = a("entity.turtle.death");
            ENTITY_TURTLE_DEATH_BABY = a("entity.turtle.death_baby");
            ENTITY_TURTLE_EGG_BREAK = a("entity.turtle.egg_break");
            ENTITY_TURTLE_EGG_CRACK = a("entity.turtle.egg_crack");
            ENTITY_TURTLE_EGG_HATCH = a("entity.turtle.egg_hatch");
            ENTITY_TURTLE_HURT = a("entity.turtle.hurt");
            ENTITY_TURTLE_HURT_BABY = a("entity.turtle.hurt_baby");
            ENTITY_TURTLE_LAY_EGG = a("entity.turtle.lay_egg");
            ENTITY_TURTLE_SHAMBLE = a("entity.turtle.shamble");
            ENTITY_TURTLE_SHAMBLE_BABY = a("entity.turtle.shamble_baby");
            ENTITY_TURTLE_SWIM = a("entity.turtle.swim");
            UI_BUTTON_CLICK = a("ui.button.click");
            UI_TOAST_CHALLENGE_COMPLETE = a("ui.toast.challenge_complete");
            UI_TOAST_IN = a("ui.toast.in");
            UI_TOAST_OUT = a("ui.toast.out");
            ENTITY_VEX_AMBIENT = a("entity.vex.ambient");
            ENTITY_VEX_CHARGE = a("entity.vex.charge");
            ENTITY_VEX_DEATH = a("entity.vex.death");
            ENTITY_VEX_HURT = a("entity.vex.hurt");
            ENTITY_VILLAGER_AMBIENT = a("entity.villager.ambient");
            ENTITY_VILLAGER_DEATH = a("entity.villager.death");
            ENTITY_VILLAGER_HURT = a("entity.villager.hurt");
            ENTITY_VILLAGER_NO = a("entity.villager.no");
            ENTITY_VILLAGER_TRADE = a("entity.villager.trade");
            ENTITY_VILLAGER_YES = a("entity.villager.yes");
            ENTITY_VINDICATOR_AMBIENT = a("entity.vindicator.ambient");
            ENTITY_VINDICATOR_DEATH = a("entity.vindicator.death");
            ENTITY_VINDICATOR_HURT = a("entity.vindicator.hurt");
            BLOCK_LILY_PAD_PLACE = a("block.lily_pad.place");
            BLOCK_WATER_AMBIENT = a("block.water.ambient");
            WEATHER_RAIN = a("weather.rain");
            WEATHER_RAIN_ABOVE = a("weather.rain.above");
            ENTITY_WITCH_AMBIENT = a("entity.witch.ambient");
            ENTITY_WITCH_DEATH = a("entity.witch.death");
            ENTITY_WITCH_DRINK = a("entity.witch.drink");
            ENTITY_WITCH_HURT = a("entity.witch.hurt");
            ENTITY_WITCH_THROW = a("entity.witch.throw");
            ENTITY_WITHER_AMBIENT = a("entity.wither.ambient");
            ENTITY_WITHER_BREAK_BLOCK = a("entity.wither.break_block");
            ENTITY_WITHER_DEATH = a("entity.wither.death");
            ENTITY_WITHER_HURT = a("entity.wither.hurt");
            ENTITY_WITHER_SHOOT = a("entity.wither.shoot");
            ENTITY_WITHER_SKELETON_AMBIENT = a("entity.wither_skeleton.ambient");
            ENTITY_WITHER_SKELETON_DEATH = a("entity.wither_skeleton.death");
            ENTITY_WITHER_SKELETON_HURT = a("entity.wither_skeleton.hurt");
            ENTITY_WITHER_SKELETON_STEP = a("entity.wither_skeleton.step");
            ENTITY_WITHER_SPAWN = a("entity.wither.spawn");
            ENTITY_WOLF_AMBIENT = a("entity.wolf.ambient");
            ENTITY_WOLF_DEATH = a("entity.wolf.death");
            ENTITY_WOLF_GROWL = a("entity.wolf.growl");
            ENTITY_WOLF_HOWL = a("entity.wolf.howl");
            ENTITY_WOLF_HURT = a("entity.wolf.hurt");
            ENTITY_WOLF_PANT = a("entity.wolf.pant");
            ENTITY_WOLF_SHAKE = a("entity.wolf.shake");
            ENTITY_WOLF_STEP = a("entity.wolf.step");
            ENTITY_WOLF_WHINE = a("entity.wolf.whine");
            BLOCK_WOODEN_DOOR_CLOSE = a("block.wooden_door.close");
            BLOCK_WOODEN_DOOR_OPEN = a("block.wooden_door.open");
            BLOCK_WOODEN_TRAPDOOR_CLOSE = a("block.wooden_trapdoor.close");
            BLOCK_WOODEN_TRAPDOOR_OPEN = a("block.wooden_trapdoor.open");
            BLOCK_WOOD_BREAK = a("block.wood.break");
            BLOCK_WOODEN_BUTTON_CLICK_OFF = a("block.wooden_button.click_off");
            BLOCK_WOODEN_BUTTON_CLICK_ON = a("block.wooden_button.click_on");
            BLOCK_WOOD_FALL = a("block.wood.fall");
            BLOCK_WOOD_HIT = a("block.wood.hit");
            BLOCK_WOOD_PLACE = a("block.wood.place");
            BLOCK_WOODEN_PRESSURE_PLATE_CLICK_OFF = a("block.wooden_pressure_plate.click_off");
            BLOCK_WOODEN_PRESSURE_PLATE_CLICK_ON = a("block.wooden_pressure_plate.click_on");
            BLOCK_WOOD_STEP = a("block.wood.step");
            ENTITY_ZOMBIE_AMBIENT = a("entity.zombie.ambient");
            ENTITY_ZOMBIE_ATTACK_WOODEN_DOOR = a("entity.zombie.attack_wooden_door");
            ENTITY_ZOMBIE_ATTACK_IRON_DOOR = a("entity.zombie.attack_iron_door");
            ENTITY_ZOMBIE_BREAK_WOODEN_DOOR = a("entity.zombie.break_wooden_door");
            ENTITY_ZOMBIE_CONVERTED_TO_DROWNED = a("entity.zombie.converted_to_drowned");
            ENTITY_ZOMBIE_DEATH = a("entity.zombie.death");
            ENTITY_ZOMBIE_DESTROY_EGG = a("entity.zombie.destroy_egg");
            ENTITY_ZOMBIE_HORSE_AMBIENT = a("entity.zombie_horse.ambient");
            ENTITY_ZOMBIE_HORSE_DEATH = a("entity.zombie_horse.death");
            ENTITY_ZOMBIE_HORSE_HURT = a("entity.zombie_horse.hurt");
            ENTITY_ZOMBIE_HURT = a("entity.zombie.hurt");
            ENTITY_ZOMBIE_INFECT = a("entity.zombie.infect");
            ENTITY_ZOMBIE_PIGMAN_AMBIENT = a("entity.zombie_pigman.ambient");
            ENTITY_ZOMBIE_PIGMAN_ANGRY = a("entity.zombie_pigman.angry");
            ENTITY_ZOMBIE_PIGMAN_DEATH = a("entity.zombie_pigman.death");
            ENTITY_ZOMBIE_PIGMAN_HURT = a("entity.zombie_pigman.hurt");
            ENTITY_ZOMBIE_STEP = a("entity.zombie.step");
            ENTITY_ZOMBIE_VILLAGER_AMBIENT = a("entity.zombie_villager.ambient");
            ENTITY_ZOMBIE_VILLAGER_CONVERTED = a("entity.zombie_villager.converted");
            ENTITY_ZOMBIE_VILLAGER_CURE = a("entity.zombie_villager.cure");
            ENTITY_ZOMBIE_VILLAGER_DEATH = a("entity.zombie_villager.death");
            ENTITY_ZOMBIE_VILLAGER_HURT = a("entity.zombie_villager.hurt");
            ENTITY_ZOMBIE_VILLAGER_STEP = a("entity.zombie_villager.step");
        }
    }
}
