name: build

on:
  push:
    branches: [ master ]
  pull_request:
  workflow_dispatch:

jobs:
  compute-cache-key:
    runs-on: ubuntu-latest
    outputs:
      cache-key: ${{ steps.compute.outputs.cache-key }}
    steps:
      - uses: actions/checkout@08eba0b27e820071cde6df949e0beb9ba4906955 # v4.3.0
      - id: compute
        run: |
          HASH=$(sha256sum .github/nms-groups.yml | cut -c1-16)
          echo "cache-key=nms-cache-${HASH}" >> "$GITHUB_OUTPUT"

  nms-cache:
    needs: compute-cache-key
    uses: ./.github/workflows/build-nms.yml
    with:
      groups-file: .github/nms-groups.yml
      cache-key: ${{ needs.compute-cache-key.outputs.cache-key }}

  build:
    needs: [compute-cache-key, nms-cache]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@08eba0b27e820071cde6df949e0beb9ba4906955 # v4.3.0

      - name: Set up JDK 8
        uses: actions/setup-java@dded0888837ed1f317902acf8a20df0ad188d165 # v5.0.0
        with:
          distribution: temurin
          java-version: 8
          cache: maven

      - name: Restore NMS Maven cache
        uses: actions/cache/restore@0057852bfaa89a56745cba8c7296529d2fc39830 # v4.3.0
        with:
          key: ${{ needs.compute-cache-key.outputs.cache-key }}
          restore-keys: |
            nms-cache-
          path: |
            ~/.m2/repository/org/spigotmc/spigot

      - name: Build and Test
        run: |
          mvn --batch-mode --show-version --no-transfer-progress \
          clean \
          test \
          verify

